### ISSUE TITLE
with_layout producing inconsistent padding

### ISSUE THREAD

**Issue by Cthutu** [emilk/egui#1040]
**Describe the bug**
When using `Ui::with_layout` within a scroll area to render a list of elements, the first entry has lots of padding around a widget added within the layout.  It seems to expand it to the whole scroll area:

![image](https://user-images.githubusercontent.com/348614/148137372-47c94ee2-0186-471a-8bc6-7ff65cb9696b.png)

Scrolling down a little you can see that the other elements rendered exactly the same way (within a for loop) are correct:

![image](https://user-images.githubusercontent.com/348614/148137422-be350598-19f1-448b-a0e3-672cc1b5fa9b.png)

**To Reproduce**

Here is the snippet of the code that produces it:

```rust
    fn update(&mut self, ctx: &CtxRef, _frame: &Frame) {
        CentralPanel::default().show(ctx, |ui| {
            ScrollArea::vertical()
                .auto_shrink([false, false])
                .show(ui, |ui| self.render_news_cards(ui));
        });
    }

    fn render_news_cards(&self, ui: &mut Ui) {
        for a in &self.articles {
            ui.add_space(PADDING);
            let title = format!("► {}", a.title);
            ui.colored_label(WHITE, title);

            ui.add_space(PADDING);
            let desc = Label::new(RichText::new(&a.desc).text_style(TextStyle::Button));
            ui.add(desc);

            ui.style_mut().visuals.hyperlink_color = CYAN;
            ui.add_space(PADDING);
            ui.with_layout(Layout::right_to_left(), |ui| {
                ui.add(Hyperlink::from_label_and_url("read more 🔗", &a.url));
            });

            ui.add_space(PADDING);
            ui.add(Separator::default());
        }
```
**Expected behavior**
I expected the padding to not be expanded on first use of `with_layout`.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This was adapted from a youtube tutorial (https://www.youtube.com/watch?v=NtUkr_z7l84) that used an older version of eframe/egui.  It works fine in his version.

**Comment by emilk** [comment]
Can you try to distill it down to a minimal stand-alone repro?

**Comment by Cthutu** [comment]
I've stripped out some code and put the application at https://github.com/Cthutu/min_fail_example

Let me know if this is good enough.

**Comment by bpostlethwaite** [comment]
I've hit this exact bug just now too. Thanks for posting and creating the minimal example @Cthutu

**Comment by RootOperator** [comment]
I've not done a lot of testing but this behavior seems to present itself inside the `CentralPanel`. I have a app that uses `ui.with_layout` inside a `ScrollArea` that is within the `SidePanel` and that one works fine. but I get the same exact bug when using it inside the `CentralPanel`.

**Comment by apathyspace** [comment]
I've bisected this bug to version between [0.14.1](https://github.com/emilk/egui/commit/2ce99f3a127b49b00e2cec3f3b5ade666faa67bf) and [0.15.0](https://github.com/emilk/egui/commit/08cc07bb2d12f06d086b2baf3f1db424a933401f) (probably expected), in particular to the commit [676527a](https://github.com/emilk/egui/pull/663/commits/676527a8a58c423613fed8960f79ebb9172936bb) of pull #663 

Here's the minimal stand-alone reproducible example, which works across both versions and demonstrates the difference:
```rust
// main.rs
use eframe::{
    egui::{CentralPanel, Layout, ScrollArea,Separator},
    epi::App,
    run_native, NativeOptions,
};

struct Foo;

impl App for Foo {
    fn update(&mut self, ctx: &eframe::egui::CtxRef, _frame: &mut eframe::epi::Frame<'_>) {
        CentralPanel::default().show(ctx, |ui| {
            ScrollArea::auto_sized()
            // .auto_shrink([true;2]) here is not supported by v0.14 and doesn't help v0.15 either
            .show(ui, |ui| {
                for a in 0..3 {
                    ui.label(format!("textA{}", a));
                    ui.with_layout(Layout::left_to_right(), |ui| {
                        ui.label(format!("textB{}", a));
                    });
                    ui.label(format!("textC{}", a));
                    ui.add(Separator::default());
                }
            })
        });
    }

    fn name(&self) -> &str {
        "Foo"
    }
}

fn main() {
    let app = Foo;
    let win_options = NativeOptions::default();
    run_native(Box::new(app), win_options);
}
```
```toml
# Cargo.toml
# 0.14
eframe = "0.14"

###
# 0.15
eframe = "0.15"
```

Previous behavior can be restored by changing `true` to `false` at [line 255](https://github.com/emilk/egui/pull/663/commits/676527a8a58c423613fed8960f79ebb9172936bb#diff-9b32ad9a135c156aab2aa989d8ef4a9b01c7475333b343b873fd58c620f9cd69R255)
```rust
        if true { // here
            // Tell the inner Ui to *try* to fit the content without needing to scroll,
            // i.e. better to wrap text than showing a horizontal scrollbar!
        } else {
            // Tell the inner Ui to use as much space as possible, we can scroll to see it!
            for d in 0..2 {
                if has_bar[d] {
                    inner_child_max_size[d] = f32::INFINITY;
                }
            }
```

This part went to 0.17 and current master, however the same replacement no longer produces desired mitigation and the bug is still reproducible (with the same example bar the deprecation changes). Therefore, that's probably not where the bug is.


Here are my speculations:
- Process:
  - the first element in the list of widgets inside ScrollArea gets full size of the current window to work with
  - it fits inside, so it doesn't need a scroll bar
  - `.with_layout()` element it fills the whole available visible space and even pushes away its sibling elements
  - next widget doesn't get such a boon of space, so it doesn't expand and only takes the space it needs to
- This process repeats on every repaint (on every `fn update()`), so the first `.with_layout()` widget is always takes all available visible space, even when the widget itself is invisible. Resizing the window resizes the first widget too, while the rest of them only take what they need .
- `/// The new layout will take up all available space.` comment above `pub fn with_layout()` is there for a reason 🙃

### Workaround
Use [`pub fn allocate_ui_with_layout()`](https://docs.rs/egui/0.17.0/egui/struct.Ui.html#method.allocate_ui_with_layout)
Updating minimal example above (again, except for deprecation changes)
```rust
use eframe::egui::Vec2;
 ui.allocate_ui_with_layout(
                Vec2::new(ui.available_width(), 0.0),
                Layout::right_to_left(),
                |ui| {
                        ui.label(format!("textB{}", a));
                   });
```

**Comment by zenofsahil** [comment]
Just hit this bug on eframe version 0.18.0

**Comment by trdthg** [comment]
I also encountered this problem with 0.18
and i use `allocate_ui_with_layout` instead of `with_layout`
```rust
ui.allocate_ui_with_layout(
    Vec2::new(ui.available_width(), 1.),
    Layout::right_to_left(),
    |ui| {
        ui.add(egui::Hyperlink::from_label_and_url("read more ⤴", &a.url));
    },
);
```
The result is much better

**Comment by emilk** [comment]
The reason for this behavior is twofold:

* [`with_layout` uses up all available space](https://docs.rs/egui/latest/egui/struct.Ui.html#method.with_layout)
* horizontal layouts centers vertically (as you noted)

Both these are the intended behavior. If you don't want to use up all the available space, use [`allocate_ui_with_layout`](https://docs.rs/egui/latest/egui/struct.Ui.html#method.allocate_ui_with_layout).
If you don't want vertical centering, use `Layout::right_to_left().cross_align(Align::Min)`.


Why do horizontal layouts use centered valign? In some cases it looks nice, for instance when putting buttons and labels after each other in a menu bar (buttons and labels have different heights).

Since this seems to be biting a lot of people, I think it would make sense to add a `valign: Align` parameter to `right_to_left`, forcing users to think this through.
