### ISSUE TITLE
Checkbox without label

### ISSUE THREAD

**Issue by voelklmichael** [emilk/egui#1047]
I would like to have a checkbox without label, since a label like "" also reserves a lot of (empty) space.
This reservation looks bad in my Layout.

Possible solutions:
- change checkbox constructor to use Option<str>
- add new constructors
- add new widget

Is this a good "first contributor" issue? If so, I can try to implement this.

**Comment by emilk** [comment]
I think the simplest approach is just to treat the `text.is_empty()` case differently in `Checkbox::ui`, so that `ui.checkbox(&mut value, "")` takes up minimal space.

Feel free to implement this!

Make sure you also do it for `RadioButon` (the code for `Checkbox` and `RadioButton` are extremely similar)
