### ISSUE TITLE
Expose glow::Context via `epi::Frame`

### ISSUE THREAD

**Issue by emilk** [emilk/egui#1198]
Since we are converging on using `glow` as the rendering backend for `eframe` on both native and web, it would be quite useful to expose the glow GL context to the user, in particular in order to do paint-to-texture from within `eframe`.

This would need to be opt-in thing though (optional dependency of `epi`) and be fallible (e.g. `frame.glow_context()` should return `None` if we aren't using a glow renderer).

This would obviously be for advanced users.

I'm not sure if there is interest in this though. My thinking is that if one wants to do 3D stuff with egui, one should probably use `bevy_egui`, `egui-macrquad`, or similar. Still, `eframe` has many features these libraries lack (reactive mode, better i/o on web).

**Comment by coderedart** [comment]
there could be some considerations for the still imaginary multi-window feature. gl contexts are usually *per* window.
I don't see any negatives here. as long as it is marked unsafe, those who want to experiment can do so. some more questions:
does the user get to request a specific version of opengl (4.6?) at the start of program?
what state is okay to change (since its all global) eg: drawing into texture means changing framebuffers/attachments and maybe more exotic stuff like polygon mode /depth test / stencil test  which egui doesn't set every frame right now. 

there could be a slight chance that people will be hitting discord with a lot of opengl questions and we might need to pin renderdoc download link at the top

**Comment by emilk** [comment]
I'm now looking into adding a custom `Shape` with a callback to which the glow context will be passed. That would allow users to embed 3D stuff and other custom painting directly into an egui Ui. This will be similar to how Dear ImGui has `AddCallback/UserCallback`
