### ISSUE TITLE
Demonstrate how to fetch resources from remote api

### ISSUE THREAD

**Issue by TotalKrill** [emilk/egui#12]
Would love to have an example on how to fetch resources from using fetch or similar.

Preferably by using web-sys or some built in mechanic :)

**Comment by emilk** [comment]
First of all: `egui` is GUI library and `egui_web` is the minimum amount of code needed to get `egui` running in a browser. So HTTP requests of any kind are obviously outside the scope of the core Egui project.

That being said, Egui is shaping up to be quite useful for smaller web apps, but one key thing missing to make that possible is easy access to HTTP functionality, so it would be great if we could figure that out.

I don't have the time or desire to work on this at the moment, but I would be open to ideas and pull requests.

I think it would make sense to have this functionality outside of `egui_web`, e.g. in a separate `example_web_fetch` crate in this repo. [`web_sys` has support for the `fetch` API](https://rustwasm.github.io/wasm-bindgen/examples/fetch.html)  so what's needed is to figure out how to integrate the `async` future with `egui_web` which uses `window.requestAnimationFrame` to run and display the GUI.

In short: PR:s welcome!

**Comment by TotalKrill** [comment]
Full understanding for you points here. 

An example for egui web is also a good idea, but looking quickly into the code, I what I am looking for is to input a general event that should trigger a redraw. Be it a timer event, finished http call, serialport got an ASCII line, mqtt server sent an update or basically whatever.

Its not obvious to me where that should be added, since the widgets would have to specify that they expect a redraw on these events, and get access to these "custom" events. 

I am guessing we somehow want to inject an Event into (WebBacked/GliumBackend)->ctx->input->event ? But that Class only handles text stuff right now.

So maybe the right way is to let the users define what the custom events are through a CustomEvents<T>, put that in Context which turns into a <T>. This struct could then be populated on each redraw, or trigger a redraw through a channel. usin try_recv. which is non blockingly checking if a redraw is needed.

What do you think?

**Comment by emilk** [comment]
I want to keep Egui as simple as possible. I think the only events that should be sent to Egui are events that Egui itself needs (mouse, keyboard). Events that only the application code needs should be kept out of Egui.

`egui_web` is set up like this: it is always asking for an animation frame at full Hz (e.g. 60 Hz) but checks a `needs_repaint` boolean to see if it actually needs to do the gui/paint code. So to re-paint the GUI you just need to set that boolean on a callback. So when you get a callback that e.g. a http request is done you can update your application state and then request an Egui repaint (to show the state change to the user).

For instance, [this is the code that requests a repaint on window load/hide/show/resize](https://github.com/emilk/emigui/blob/master/egui_web/src/lib.rs#L303:L310):

``` rust
    for event_name in &["load", "pagehide", "pageshow", "resize"] {
        let runner_ref = runner_ref.clone();
        let closure = Closure::wrap(Box::new(move || {
            runner_ref.0.lock().needs_repaint = true;
        }) as Box<dyn FnMut()>);
        window.add_event_listener_with_callback(event_name, closure.as_ref().unchecked_ref())?;
        closure.forget();
    }
```

Most of the ugly part of the code is due to the web_sys bindings. `runner_ref` is what is running `Egui`.

**Comment by emilk** [comment]
I've added a very simple example of this at https://emilk.github.io/egui/example.html

It should be enough of a template to follow!

Implementation: https://github.com/emilk/egui/blob/master/egui_web/src/fetch.rs
