### ISSUE TITLE
Dragging on slider and its value behaves differently

### ISSUE THREAD

**Issue by lukors** [emilk/egui#1465]
**Describe the bug**
Dragging on a slider works even if the value being mutated isn't actually saved between frames. However, dragging on the value next to the slider does not behave the same way, the value does not change unless the changed value is saved between frames.

**To Reproduce**
Create a slider with a value that gets reset to the same value every frame, drag on the slider, then drag on the value next to the slider.

**Expected behavior**
Dragging on the slider and the value next to it should have the same behavior.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by emilk** [comment]
Is this really a problem? I would consider not saving the value between frames a bug, and so it is no surprise it leads to buggy behavior. If you want to disable changing a slider, use `ui.add_disabled`.

**Comment by lukors** [comment]
The problem is that I wasn't aware that I was expected to save the mutated value between frames and that not doing that could lead to buggy behavior. Could it maybe be solved with documentation?

The nice thing about fixing this bug is that the behavior can act as documentation. If you can't move the slider or the value when you don't save the value, you immediately understand the behavior. If you *can* move the slider and the value, you understand it as well. When they do different things, and there's no information about how it should work, it's harder to know where the issue lies. :)

**Comment by emilk** [comment]
The reason the DragValue doesn't change as you drag it is because it is showing the value from the previous frame - meaning it is less responsive than the slider. I would rather fix _that_, because it would make correct use of egui better (with less latency).

I can add some more documentation about how the user is responsible for storing app state to https://docs.rs/egui/latest/egui/#understanding-immediate-mode
