### ISSUE TITLE
derive forms from data 

### ISSUE THREAD

**Issue by tami5** [emilk/egui#1481]
**Is your feature request related to a problem? Please describe.**

Data is important for UI, it would be nice if data can be converted to standard form users can input form. 

This is particularly important for fast prototyping and testing.

**Describe the solution you'd like**

custom derive_macro to be added to `derive()` like `Form`. For form to work maybe the struct/enum needs to implement serde.

**Describe alternatives you've considered**

```rust
        ui.horizontal(|ui| {
            ui.label("Field");
            ui.text_edit_singleline("value");
        });
```
for every field.

**Comment by coderedart** [comment]
https://github.com/crumblingstatue/egui-inspect works for you maybe?

but it is true that for a lot of apps, having this kinda stuff in egui_extras or somewhere more official would make it much easier to start with. and then later write custom ui code if necessary.

**Comment by emilk** [comment]
I agree that this is something very useful and nice to have, but I also think it can be a separate crate (because I don't feel like maintaining something like that right now). I'd suggest either improving https://github.com/crumblingstatue/egui-inspect (which is inspired by https://github.com/aclysma/imgui-inspect) or creating something new!
