### ISSUE TITLE
Always use consistent triangle winding

### ISSUE THREAD

**Issue by icefoxen** [emilk/egui#154]
**Describe the bug**
As described in https://docs.rs/epaint/0.8.0/epaint/struct.Triangles.html#structfield.indices , `egui` isn't consistent in which order it generates vertices for triangles, so you have to disable backface culling.  Personally I consider this poorly behaved, and it makes life more complicated for a user or renderer for no particular gain.  This makes it more troublesome to integrate egui with various graphics systems or game libs.  

In `tetra` for example you have to switch the winding mode whenever you draw `egui` stuff, then switch it back unless you're fine drawing the backs of every triangle.  Some frameworks, like `ggez`, don't even have an option to switch winding mode, so you can't use `egui` with them.  Enabling backface culling also improves performance slightly, and having to switch it back and forth to draw GUI stuff certainly degrades it.

**To Reproduce**
N/A, documented behavior.

**Expected behavior**
Only ever generate triangles with a CCW winding.  A simple but perhaps slow method would be to just walk through all the triangles before they're drawn and re-order their indices appropriately; I can try to submit a PR to do this if you want.  I don't know enough about `egui`'s internals to know more.

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: 0.8.0

**Comment by emilk** [comment]
I don't consider this a bug - this is an intentional choice (whether or not it is a good choice is up for discussion!).

Backface culling was invented to speed up 3D rendering (where backfaces are a thing) - it was never designed for 2D. Consistent winding order is very important to get right in 3D (this is where it improves performance) – in 2D it doesn't matter.

If `ggez` doesn't have an option to turn it off, I would consider that to be a flaw in `ggez` rather than in egui. A simple (but somewhat expensive) fix would be to go through the triangles that egui outputs and flip the wrong ones before handing them over to `ggez`.

---

If egui should output triangles in a consistent winding order there are many questions that needs to be answered, like:

What happens if a user adds a custom [`Shape`](https://docs.rs/epaint/0.8.0/epaint/enum.Shape.html) with triangles in the wrong winding order - should egui detect this and flip them, or is it up to the user to get it right? In the first case we punish performance, in the second case we make egui harder to use (forcing people to get their winding order correct).

CW or CCW? What is the default/expected on OpenGL, wgpu, vulkan, metal etc? Is there a consistent standard? If we get this wrong it will be even *worse* than the status quo.

Currently if an integration turns on backface culling for egui it is obvious what is wrong (as you get obvious missing triangles). If egui instead spits out all triangles in CW and the backface is accidentally set to CW, then the integration will show nothing, leading to a much harder debug.

Finally: if we turn on backface culling by default it will leave to hard-to-detect bugs like "why isn't my new widget showing up on screen?". We could add wrong-order detection to the egui tesselator or backend to help here, but it would again hurt performance.

---

All this said just to drive home the point that this is not an easy or obvious change. It requires a lot of design work and thought to get just right.

In my opinion it is easier to just disable backface culling.

**Comment by icefoxen** [comment]
> CW or CCW? What is the default/expected on OpenGL, wgpu, vulkan, metal etc? Is there a consistent standard?

OpenGL, Vulkan, and WebGPU are CCW by default.  Metal and DX11/12 are CW by default.  Sorry about that, I'd thought that everything was CCW everywhere and so this would be a lot easier.

AFAIK the performance impact to drawing backfaces isn't doing the actual drawing, but in changing the drawing mode.  In OpenGL this involves toggling a global, of course, which I would expect is a potential pipeline stall.  In Vulkan it's defined by the pipeline, so changing it is similar in impact to changing a shader or shader layout.  On the other hand it seems likely you'd have a separate shader for UI drawing anyway.

**Comment by Elinvynia** [comment]
Relevant: https://github.com/ggez/ggez/issues/902
