### ISSUE TITLE
How I use unreleased version with wgpu 0.13 ?

### ISSUE THREAD

**Issue by zhouhang95** [emilk/egui#1822]
```
wgpu = "0.12"
egui-wgpu = "0.18"
egui = "0.18"
egui-winit = "0.18"
```

now, I want to use wgpu 0.13
how to change cargo file?

**Comment by alexanderameye** [comment]
I bumped wgpu to 0.13 and then did

`egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
egui-winit = { git = "https://github.com/emilk/egui" }`

because otherwise I got a version of cargo not figuring out what version of web-sys to use

This compiles, however I am having issues with egui and wgpu 0.13 so waiting for an actual release in the future.
