### ISSUE TITLE
[suggestion] remove .text from slider and make value box configurable

### ISSUE THREAD

**Issue by Wumpf** [emilk/egui#183]
Currently Slider shows text optional to the right side, but this is also tied to whether the value box is displayed. So I found myself doing
```
ui.horizontal(|ui| {
    ui.label("description");
    ui.add(egui::Slider::f32(&mut some_value, 0.0..=1.0).text(""));
});
```
to get it onto the left side (or similar to get it into a grid), which seems a bit silly. It probably would be best to not have `.text` integrated in the slider, as most other widgets don't have that either and instead have an option to enable/disable the value box.
I can do a PR if that change is welcome :)

**Comment by t18b219k** [comment]
I suggest adding a .news (east, west, north, south) field and keeping .text

**Comment by emilk** [comment]
I agree that is is very silly that the `text(…)` member also controls whether or not the value shows.

The plan I had in mind is to change `Slider` to always show the value (at least by default, perhaps with an option to turn it off) and keep the `text(…)` member, as it is a nice convenience (and for backwards compatibility).

The motivation for having a label in the first place it to be symmetrical with how `Checkbox` and `RadioButton` have texts attached to them, and because you more often than not want text attached to a slider.

**Comment by Wumpf** [comment]
Makes sense, thanks for following up and taking the time to not only fix it but also explain what's going on :)
