### ISSUE TITLE
Window resize not following cursor in wasm demo

### ISSUE THREAD

**Issue by ChevyRay** [emilk/egui#206]
**Describe the bug**
Incorrect resizing behavior when resizing a window in the egui wasm demo. The corner of the window, when grabbed, does not correctly follow the cursor.

**To Reproduce**
1. Go to [https://emilk.github.io/egui/](https://emilk.github.io/egui/)
2. Enable the "⬌ Window Resize" example
3. Resize the "⬌ Resizable" window

**Expected behavior**
The corner, when grabbed, should follow the mouse cursor.

**Screenshots**
![resizing bug](https://media.giphy.com/media/9q30sI1vqUfaZHg4qD/giphy.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Browser: Google Chrome 88.0.4324.192

**Comment by emilk** [comment]
This is intended behavior. There are other resize demos that shows that you need a scroll area for the desired behavior.

**Comment by ChevyRay** [comment]
oh really? that is super wild.

sorry for the false report, then! cheers

**Comment by emilk** [comment]
I can add some better descriptions in the demo. The short of it is: without a scroll area there is no way to resize the window because I don't want to clip the contents or shrink the text. And having a scroll area should be optional. See the `resizable + embedded scroll` or ` resizable + scroll` demo windows for  the requested behavior
