### ISSUE TITLE
Split backend functionality 

### ISSUE THREAD

**Issue by t18b219k** [emilk/egui#207]
**Is your feature request related to a problem? Please describe.**

I'm writing backend code for wgpu and vulkano and using same io platform egui_winit_platform 
but setting storage , http and window position is part of egui_glium  .
This problem cause lack of reusability 
Backend need to be more portable and flexible for support other platforms for example DirectX9 platform , Metal platform  Nintendo Switch (Rusted Switch project exists)
**Describe the solution you'd like**
split setting storage and http

**Comment by emilk** [comment]
If you want to implement the full `epi::App` then yeah, it would be nice to extract the `http` etc parts. But I don't expect integrations to do so - `epi` is only so I can have a unified interface for `egui_web` and `egui_glium`.

See for instance https://github.com/not-fl3/emigui-miniquad which doesn't have its own http support.

My hope is that in the future it will be more common with rust crates that support web. So for instance: instead of `egui_glium` using `ureq` and `egui_web` using web-sys, maybe `ureq` (or some other crate) could support web requests that work both on native and with web backends. I only added an abstraction layer on top of that because I couldn't find a library that already did that. Personally I have no desire to build interfaces over things like http, persistence and clipboard - I'd much rather if the clipboard crate just worked even when compiling for the web.

**Comment by parasyte** [comment]
See also #212 for some additional concerns and provided context.
