### ISSUE TITLE
Unable to paste from clipboard while egui application is running

### ISSUE THREAD

**Issue by apexys** [emilk/egui#2109]
**Describe the bug**
I'm building an application based on egui (master branch).
While this application is running, I am unable to use the clipboard on Windows 10.0.19043.
If I copy text, I can not paste it. 
When I take a screenshot with Win-Shift-S, I get the pop-up, even showing the screenshot, but I am unable to paste it.
If it helps, it seems the application I'm pasting into hangs for a very short time (500ms?) after Ctrl-V.

**To Reproduce**
1. Clone the egui repo and run the demo app with `cargo run --release -p egui_demo_app`
2. Copy text from any window or take a screenshot
3. Try to paste it somewhere

**Expected behavior**
The copied content is inserted.

**Comment by emilk** [comment]
Pasting images is not yet supported (see https://github.com/emilk/egui/issues/2108), but copy-pasting of text should work. Since nobody else has reported copy-paste not working on Windows, I would suggest this is something weird with your system.

Look in `crates/egui-winit/src/lib.rs:538` and see if `is_paste_command` detect `Ctrl-V`, and if so, if `self.clipboard.get()` returns anything.

Also: run with `RUST_LOG=debug` and see if the log gives any clues

**Comment by apexys** [comment]
Thank you for your answer!

Maybe my issue was a bit non-specific:
I'm not talking about copying and pasting within egui, but between completely unrelated applications while an egui application is running in the background.
I tried disabling the clipboard feature in egui_glow, but since I'm using eframe, it just gets enabled again in https://github.com/emilk/egui/blob/master/crates/eframe/Cargo.toml#L82 
Is there a way to completely disable clipboard integration with eframe?

I tried this on several computers running Windows 10 and the issue happens everywhere.

**Comment by apexys** [comment]
I guess this is related to https://github.com/emilk/egui/pull/1031

**Comment by emilk** [comment]
The commit that broke it should be https://github.com/emilk/egui/pull/2067

**Comment by apexys** [comment]
Thank you for the quick fix!
