### ISSUE TITLE
Allow the use of non-static App

### ISSUE THREAD

**Issue by Gnurfos** [emilk/egui#2152]
I have some struct offering a view over something, not owning but storing a reference to that something:

```rust
struct Reader<'a> {
    buffer: &'a[u8],
}

impl<'a> Reader<'a> {
    pub fn get(&self, i: usize) -> u8 {
        self.buffer[i]
    }
}
```

I'd like to use that reader to run an egui app:

```rust
struct ViewerApp<'a> {
    reader: Reader<'a>,
}

impl<'a> eframe::App for ViewerApp<'a> {
    fn update(&mut self, ctx: &egui::Context, _: &mut eframe::Frame) {
        eframe::egui::CentralPanel::default()
            .frame(eframe::egui::Frame::none())
            .show(ctx, |ui| {
                ui.label(format!("Buffer slot 0: {:?}", self.reader.get(0)));
            });
    }
}
```
However, from the way `AppCreator` is declared, I think it can only accept things with `'static` lifetimes:
```rust
fn main() {
    let buffer = vec![0u8; 100];
    let reader = Reader { buffer: &buffer };
    visualize(reader);
}

fn visualize<'a>(reader: Reader<'a>) {
    eframe::run_native(
        "Buffer visualizer",
        eframe::NativeOptions::default(),
        Box::new(|_| Box::new(ViewerApp { reader })),
    );
}
```
Fails with:
>  |         Box::new(|_| Box::new(ViewerApp { reader })),
>  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cast requires that `'a` must outlive `'static`

I tried various workarounds but the only way I could "solve" this was by doing:
```rust
    let reader = unsafe {
        std::mem::transmute::<_, Reader<'static>>(reader)
    };
```
to "cast away" the lifetime, assuming that the items are alive at least until run_native returns.
It appears to work, but I'm not sure it's safe in every situation.

Ideally, run_native would accept something with lifetimes, so that the code above just works.
Alternatively, but I'm just guessing, this could be achieved by replacing AppCreator by a trait other than FnOnce.

I have no idea if either of these is feasible, or if that would pollute the api in unacceptable ways.

**Comment by Speak2Erase** [comment]
Take a look at `Box::leak`?

**Comment by Gnurfos** [comment]
I think I tried but it doesn't change the lifetime issue. And leaking is not great, now that run_native can return and be called several times in an app.

**Comment by Speak2Erase** [comment]
Ah true

**Comment by andoalon** [comment]
Just had the same issue. In my case I put the data I want to refer to in an `Rc`, which works but shouldn't be necessary.

I believe the issue comes down to using `Box<dyn ...>` for the `AppCreator` (`dyn` implies `+ 'static`: https://stackoverflow.com/questions/72672953/cast-requires-that-variable-is-borrowed-for-static).

I'm not sure if the cause is that the `AppCreator` itself being in `Box<dyn FnOnce(...) -> ...>`, or that it has to return `Box<dyn App>` (or maybe it's both)

**Comment by timstr** [comment]
I'd also love to be able to have a non-`'static` AppCreator. I'm working with the [Inkwell](https://github.com/TheDan64/inkwell/) crate which provides a `Context` object that virtually everything borrows from and stores a lifetime from. Storing this in the egui App is not an option because I need to store things with lifetimes between update calls, and that basically amounts to a self-referential App struct otherwise. I also found that this results from the `AppCreator`'s use of trait objects which implicitly imply `'static`. I'm looking into adding an explicit lifetime to the `AppCreator` type, hopefully without upheaving the existing API
