### ISSUE TITLE
`DragValue::clamp_range(0.0..=max)` allows `-0.0`

### ISSUE THREAD

**Issue by SludgePhD** [emilk/egui#2203]
**Describe the bug**

Using `DragValue::clamp_range(0.0..=max)` to force a `DragValue` to be positive does not fully work: It allows the value to be dragged to `-0.0`, which can then cause other methods to fail (eg. [`Duration::from_secs_f32`](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.from_secs_f32)).

While `0.0` and `-0.0` compare equal, `is_sign_negative` will still return `true`, since the sign bit is set in the value.

**To Reproduce**
1. Create a `egui::DragValue::new(&mut value).speed(0.01).clamp_range(0.0..=f32::MAX)`
2. Drag it to `0.01`
3. Drag it downwards
4. (might require some fiddling, it doesn't always happen)

**Expected behavior**

I would not expect to see any values with the sign bit set if `.clamp_range(0.0..=f32::MAX)` is used.

**Desktop (please complete the following information):**
 - OS: Linux (Wayland) with winit/bevy, but this does not look like platform-specific behavior

**Comment by ItsEthra** [comment]
This happens because `clamp`, `min` and `max` functions used by `clamp_to_range` in file `drag_value.rs:510` are not using `total_cmp`. One easy fix is to implement it manual clamping using [total_cmp](https://doc.rust-lang.org/std/primitive.f64.html#method.total_cmp) but this would require bumping minimum supported rust version from 1.61 to 1.62.
