### ISSUE TITLE
Are egui and SDL2 compatible?

### ISSUE THREAD

**Issue by gamecubate** [emilk/egui#24]
I'd like to integrate egui with my app (currently in development and in the process of picking a UI lib). It uses SDL2 for canvas, events, windows, etc.

Do you know of any issues running those two together (on Win, macOS, Linux)?

**Comment by emilk** [comment]
Hello!

As far as I know, nobody has made an SDL2 backend for Egui yet, so you can be the first!

How difficult this is depends on one things: are you using an OpenGL renderer with SDL2?

If yes, you can follow this short guide: https://github.com/emilk/egui#writing-your-own-egui-backend

However, if all your working with is [`sdl2::render::Canvas`](https://docs.rs/sdl2/latest/sdl2/render/struct.Canvas.html) then you are going to have a harder time. In particular, the current structure of Egui expects you to be able to quickly paint textured triangles, which the SDL2 `Canvas` API does no support.

I have some plans for exposing [`egui::PaintCmd`](https://docs.rs/egui/0.1.4/egui/paint/command/enum.PaintCmd.html) as the output of Egui. This would allow backends that work on higher level primitives such as rectangles, lines and text instead of just triangles. But writing a painter for `egui::PaintCmd` will probably be more work than a standard triangles based one.

**Comment by gamecubate** [comment]
Hi @emilk !

Using the SDL2 canvas is exactly what I am doing right now for content creation (drawing to Surface buffers...
```
let mut canvas: WindowCanvas = win.into_canvas().build().unwrap();
...
// Palette and working colors
let mut pal: Palette = init_palette();
...
let mut bg_color = pal.get("c8");
...
// Buffers and roles
let (w, h) = canvas.window().drawable_size();
let mut a_s = Surface::new(w, h, PixelFormatEnum::RGBA32).unwrap();
let mut draw_s = &mut a_s;
...
// Pre-render
render(&mut draw_s, &mut canvas, bg_color);
canvas.present();

// Event loop and handlers
let mut pump = sdl.event_pump().unwrap();
'running: loop {
...
}

// Render
render(&mut draw_s, &mut canvas, bg_color);
canvas.present();
thread::sleep(time::Duration::from_millis(sleep_ms));
...
```

<thinking aloud> : is there anything preventing me from managing both a canvas (for buffer manipulations) _and_ the OpenGL renderer from one same app? OGL could be used for egui and the canvas for the rest.

Thanks!
