### ISSUE TITLE
TextEdit::singleline() and multiline() invisible

### ISSUE THREAD

**Issue by L1ghtingBolt** [emilk/egui#2403]
**Describe the bug**
adding a `TextEdit::singleline()` or `multiline()` add up the space ad shows the caret on the cursor, but is not visible nor clickable

**To Reproduce**
1. Make a minimal project (for example, the eframe example)
2. Add `ui.text_edit_singleline()` (or `multiline`)
3. Compile
4. Nothing appears

**Expected behavior**
I expect a text editor to appear and be usable, but there's nothing.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/82386159/205955502-f0802983-a6ca-4018-a73a-0679bda91f50.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser 
 - Version master branch

**Additional context**
I tried using add() and text_edit_singleline, but none of them work.

**Comment by emilk** [comment]
Does [the `hello_world`](https://github.com/emilk/egui/tree/master/examples/hello_world) example work for you?

**Comment by L1ghtingBolt** [comment]
Same problem. Input does not appear

**Comment by emilk** [comment]
That is very weird. I think it is up to you to debug this, since it works on my computer

**Comment by L1ghtingBolt** [comment]
![imagen](https://user-images.githubusercontent.com/82386159/206437407-1d59465a-f618-4903-b1f4-1bb970fd0a5d.png)

also happening under WSL

**Comment by L1ghtingBolt** [comment]
![imagen](https://user-images.githubusercontent.com/82386159/206439063-c9ffb732-d949-445c-ba3e-cd22b305045c.png)
If I put a default text it appears and I can select it, but cannot modify it tho.

**Comment by DrOptix** [comment]
Looking at your code I see the mistake.

You declared `text` inside the `update()` function and then you want to modify it with the `singelline()`, well that kind of works, it it isn't. If memory serves me well when you want to modify text in the `singleline` it will be reflected only for one frame. Then you reinitialize `text` inside the `update()` functions and so on.

That's why you can't change it.

Move it into your struct `MyEguiApp`.

```rust
#[derive(Default)]
struct MyEguiApp {
    text: String,
}
```

Then modify update like this:
```rust
ui.add(widget::TextEdit::singleline(&mut self.text));
```

Also what I'm not sure of is how `singleline()` and `multiline()` deal with `&str` instead of `String`, but before digging deeper let's try my suggested patch.

PS: Next time don't put a screenshot of your code. It is much better to put your code in a code block so we can easy patch it and point out potential mistakes.
