### ISSUE TITLE
Save plot to image file

### ISSUE THREAD

**Issue by cdhf** [emilk/egui#2470]
**Is your feature request related to a problem? Please describe.**
I am using the plot widget to visualize log data for failure analysis of hardware systems. I often need to save the plots to image files to include them in written reports. Often I need the info shown for the current mouse position as well, so I need to make a screenshot of the whole desktop, paste that into a separate program and then clip the image to the desired region.

**Describe the solution you'd like**
It would be great if there was builtin functionality to save a plot to an image file with user defined size. It would be even better, if there was a way generic way to save some part of the window to an image.

**Describe alternatives you've considered**
I've looked at the screenshot example, but it seems that I can only get a screenshot of the whole window, and that the quality of the image is limited.

**Comment by saturn77** [comment]
I am having the same issue, in terms of figuring out a way to save the plot image only to an image. 

Since I have the plot points available in a buffer in egui, one options is to simply make a button such as "save plot image" which would then use the current PlotPoints and write them to a png file. 

Since matplotlib is kind of a standard, one consideration is to use one of the the Rust ports of matplotlib to create a PNG file from the data.

**Comment by hacknus** [comment]
I would also really be interested in a egui built-in solution!

**Comment by dashdeckers** [comment]
I would love this as well! Would be an amazing feature for those using egui to visualize data to be able to save those visualizations.
