### ISSUE TITLE
Clickdetection: Allowed time between press and release of mousebutton becomes too low on high fps

### ISSUE THREAD

**Issue by Q4LEX** [emilk/egui#2502]
**Describe the bug**
egui click detection seems to be based on the amount of renders, not the amount of time between the button events.
Meaning -> Applications with high fps are unable to detect human mouse clicks (Problems start at roughly 300hz).

**To Reproduce**
1. Implement an Application that redraws egui frames in high fps (>300)
2. Add a clickable ui element
3. Try to click it normally -> Nothing happens
5. Try to click it fast -> Click registers

**Expected behavior**
I expected the allowed interval between button up and down to be based on time and not render events.
But maybe I'm wrong -> Sorry If I'm wrong

Tested on Master Branch of egui and egui-wgpu.

**Comment by parasyte** [comment]
The click duration is time-based (not frame-based), but it turns out that passing a delta time to the input handler is optional, and it defaults to an assumption that the frame rate is 60 Hz.

The click duration is 600ms: https://github.com/emilk/egui/blob/6c4fc50fdf5ab4866ee29669c110e178b741c8e9/crates/egui/src/input_state.rs#L14-L15

`InputState::begin_frame` gets the delta time from the `RawInput`, with a fallback to `RawInput::predicted_dt`: https://github.com/emilk/egui/blob/6c4fc50fdf5ab4866ee29669c110e178b741c8e9/crates/egui/src/input_state.rs#L139-L146

The `predicted_dt` is documented with: https://github.com/emilk/egui/blob/6c4fc50fdf5ab4866ee29669c110e178b741c8e9/crates/egui/src/data/input.rs#L42-L45

----

Given this info, I might suspect that the platform integration you are using may not be passing the correct delta time to `Context::run()`. If you are using `egui_winit::State::take_egui_input()` (including via `eframe` and `egui_glium`), it should do the right thing to update the time input: https://github.com/emilk/egui/blob/34f587d1e1cc69146f7a02f20903e4f573030ffd/crates/egui-winit/src/lib.rs#L182

This is making a lot of assumptions, but the way clicks are handed in `egui` _appears_ to be what we would expect.

A small example that reproduces the issue might help track down where it is going wrong.

**Comment by Q4LEX** [comment]
Alright, It was just me not realizing to provide the time to RawInput.
(I am using egui_wgpu and my own winit integration).

Thanks!
