### ISSUE TITLE
Please describe runtime dependencies in the README

### ISSUE THREAD

**Issue by yurivict** [emilk/egui#2547]
The pw-viz project uses egui and the binary isn't linked with any graphics-related shared libraries.
When the binary runs it loads these:
```
/usr/local/lib/libGL.so.1.7.0
/usr/local/lib/libGLX.so.0.0.0
/usr/local/lib/libGLX_nvidia.so.0
/usr/local/lib/libGLdispatch.so.0.0.0
/usr/local/lib/libX11-xcb.so.1.0.0
/usr/local/lib/libX11.so.6.4.0
/usr/local/lib/libXau.so.6.0.0
/usr/local/lib/libXcursor.so.1.0.2
/usr/local/lib/libXdmcp.so.6.0.0
/usr/local/lib/libXext.so.6.4.0
/usr/local/lib/libXfixes.so.3.1.0
/usr/local/lib/libXi.so.6.1.0
/usr/local/lib/libXrandr.so.2.2.0
/usr/local/lib/libXrender.so.1.3.0
/usr/local/lib/libdbus-1.so.3.32.1
/usr/local/lib/libnvidia-glcore.so.1
/usr/local/lib/libnvidia-glsi.so.1
/usr/local/lib/libnvidia-tls.so.1
/usr/local/lib/libpipewire-0.3.so.0.362.0
/usr/local/lib/libxcb-glx.so.0.0.0
/usr/local/lib/libxcb.so.1.1.0
```

What is the minimal list of run-time dependencies?

**Comment by parasyte** [comment]
That depends on which backend the `pw-viz` project uses, and thereby on which dependencies the backend needs.

`egui-wgpu` for instance only statically depends on X11 if the `wgpu` feature is enabled for it at build-time. Everything else is dynamically loaded.

`egui-glutin` possibly also uses dynamic loading, since `glutin` supports multiple GL implementations.

For other backends, different linking strategies may apply.

**Comment by yurivict** [comment]
I see, thank you.
