### ISSUE TITLE
Keep filedialog in front of main window with eframe - Add the `HasRawWindowHandle` to `eframe::Frame` maybe?

### ISSUE THREAD

**Issue by willmendil** [emilk/egui#2757]
**Is your feature request related to a problem? Please describe.**
When using `rfd` to open a file fialog window, It easly goes behind the main window, freezing the latter and confusing the user. 
I know this is a solved issue with egui-winit, since it is possible to give to rfd::FileDialog().set_parent(var [of type winit::window::Window])

**Describe the solution you'd like**
However, when using eframe, i cannot seem to find the window that was generated when the frameware ran `winit::windw::WindowBuilder`. I don't think it is public. 
In the main update loop, i have the `ctx` and the `frame`, and it would be good if `frame` had the  `HasRawWindowHandle`  `rfd` requires to be set as parent.

**Describe alternatives you've considered**
I tried directly using the egui-winit example, but I have mean drawbacks specifically in terms of quality of the rendering. eframe has been the best performing for me

**Additional context**
Some of the docs are below

https://docs.rs/winit/0.28.1/winit/window/struct.Window.html#method.raw_window_handle
https://docs.rs/raw-window-handle/0.5.0/raw_window_handle/trait.HasRawWindowHandle.html
https://docs.rs/rfd/latest/rfd/struct.FileDialog.html#method.set_parent

**Comment by mvirkkunen** [comment]
Having access to the raw window and display handles would be useful for other things as well, for example right now I need it for a third party native library. It think `Frame` and `CreationContext` would be the best places to add them, because that's where the renderer contexts are available as well. `WindowInfo` would result in less duplication and cfg attributes, but unfortunately that one is clonable, and therefore could be kept around after the window has been destroyed, breaking the safety requirements of `HasRawWindowHandle`.

I have a quick implementation I already made for testing - should I clean it up and PR, or is somebody working on this already?

**Comment by willmendil** [comment]
I'd like to see your implementation at least in the mean time

**Comment by mvirkkunen** [comment]
@willmendil It's not very complicated:

https://github.com/mvirkkunen/egui/commit/a4113c57226ba5ee0904a86aa298971d17f7c13c#diff-ff3581c7997aa722047969018c3fe1418992ea044a798557ce7b606b3a45cd14L18

Just need to run all the tests and such and possibly clean some things up.

**Comment by emilk** [comment]
Looks like a good addition - please open a PR!
