### ISSUE TITLE
Keyboard navigation: focus change loses new value in DragValue

### ISSUE THREAD

**Issue by tajtiattila** [emilk/egui#2877]
In the Widget Gallery of Egui Demo, focus the DragValue and type in a new number. Tab or Shift+Tab moves the focus to the next widget, but the new value is lost. The value is kept only when Enter is pressed, but then the focus is lost.

https://user-images.githubusercontent.com/247562/230308477-13e59cd0-e612-49f8-acaf-a7b36c848b23.mp4

This somewhat defeats keyboard navigation with DragValues because one can either navigate or change values, but not both.

**Expected behavior**
DragValue should keep the value entered when Tab is pressed.

Tested on the web demo at egui.rs and eframe on Windows using egui version 0.21.3-28-geb0812a9 (2023-03-31).

There seems to be a related issue: the internal state of the TextEdit/DragValue (text cursor position, selection) seems to be remembered when navigating away with Tab, and is reset only when focusing the widget with the mouse (which selects the whole number). Perhaps focusing the DragValue with Tab should work like focusing with the mouse.

**Comment by harrisonmg** [comment]
relevant: #2880

**Comment by YgorSouza** [comment]
The code that decides whether the value should be updated is this:

https://github.com/emilk/egui/blob/d77c44657206d6a5a9eda0d3b10fac6e189acc27/crates/egui/src/widgets/drag_value.rs#L494-L500

The code is conditional on the `is_kb_editing` variable defined here:

https://github.com/emilk/egui/blob/d77c44657206d6a5a9eda0d3b10fac6e189acc27/crates/egui/src/widgets/drag_value.rs#L389-L400

It seems that the problem is that on the frame where the TextEdit would lose focus after pressing tab, `is_kb_editing` is already set to false, so we never get the `lost_focus` condition to update the value. We get it with Enter because in that case the TextEdit itself calls surrender_focus on the same frame:

https://github.com/emilk/egui/blob/d77c44657206d6a5a9eda0d3b10fac6e189acc27/crates/egui/src/widgets/text_edit/builder.rs#L967-L981

Given that, I wonder what would be the best way to fix it. Maybe we could change the logic for `is_kb_editing` to render an extra frame after focus is lost, but that would mess with accessibility, according to the comment. Another option would be to add a `pub(crate)` method to `TextEdit` that would make it capture the Tab key and surrender focus manually like it does with Enter, but that seems a little convoluted.
