### ISSUE TITLE
Layouting regression in 0.11

### ISSUE THREAD

**Issue by jakobhellermann** [emilk/egui#289]
With the following code
```rust
egui::CentralPanel::default().show(ctx, |ui| {
    ui.with_layout(egui::Layout::left_to_right(), |ui| {
        ui.label("Inside");
    });
    ui.heading("Outside");
});
```

the layout takes up all the vertical space and the "Outside" label is barely visible.

![Screenshot from 2021-04-10 13-33-50](https://user-images.githubusercontent.com/22177966/114268441-6da35e80-9a01-11eb-9dca-d3799ea1b051.png)

**Comment by emilk** [comment]
This is intentional, though not well documented.

A new layout takes up all available space, so in this case `inside` is the only label in the left-to-right layout (and is vertically centered). You can use `ui.allocate_ui_with_layout` to specify how much space to use, or the helper `ui.horizontal` (which is probably what you want to use in this case).
