### ISSUE TITLE
epi::App API for registering timer based callbacks

### ISSUE THREAD

**Issue by chamons** [emilk/egui#295]
**Is your feature request related to a problem? Please describe.**
I need the ability to react after a period of time (say every 0.25 seconds), and as as epi::App owns the event loop I'm having trouble figuring out how to register for a timer callback.

The update function is called every second or on mouse move\repaint.

**Describe the solution you'd like**
Expose either a non-render update API on epi::App or the ability to register for a timer callback on the UI thread.

Or explain what I'm missing. :)

**Describe alternatives you've considered**
I've poked around the API and demo app and haven't found an entry point.

**Additional context**

**Comment by chamons** [comment]
It appears the demo app uses continuous repainting:

        if self.run_mode == RunMode::Continuous {
            // Tell the backend to repaint as soon as possible
            ctx.request_repaint();
        }

Which sounds locked to the refresh rate?

**Comment by emilk** [comment]
The demo mode has both a reactive and continuous mode (hence the `if`). You can switch in the backend panel: https://emilk.github.io/egui/index.html

Yes, adding a timer callback to `epi` would make sense. There is one hacky way of doing it now with [`Frame::repaint_signal`](https://docs.rs/epi/0.11.0/epi/struct.Frame.html): clone the signal, spawn a thread, sleep in it, then trigger the signal. A bit wasteful, but should work until this issue is resolved.

**Comment by coderedart** [comment]
@emilk I think this issue can be closed now that we have a [request_repaint_after](https://docs.rs/egui/latest/egui/struct.Context.html#method.request_repaint_after) which allows setting timeout for UI thread.
