### ISSUE TITLE
Wayland build error without wayland feature

### ISSUE THREAD

**Issue by LinusU** [emilk/egui#3038]
**Describe the bug**
I'm trying to run egui on an [Olimex Allwinner A13 board](https://www.olimex.com/Products/SOM/A13/) which I'm running Linux 3.4.90 on. There is a few qt applications running, so I'm guessing that it has X11.

I have added eframe to my empty project using `cargo add eframe`. It shows that the feature `wayland` isn't enabled:

<img width="331" alt="Screenshot 2023-05-31 at 22 11 07" src="https://github.com/emilk/egui/assets/189580/fd81f9f0-e5bd-4904-af98-776121699a94">

But when trying to build the project, it fails with a build error in `winit-0.28.6/src/platform_impl/linux/wayland/protocols.rs`:

```text
error: couldn't read /Users/linus/coding/brewie-egui/target/armv7-unknown-linux-musleabihf/release/build/winit-bffde51e9e2d0966/out/fractional_scale_v1.rs: No such file or directory (os error 2)
  --> /Users/linus/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.6/src/platform_impl/linux/wayland/protocols.rs:13:1
   |
13 | include!(concat!(env!("OUT_DIR"), "/fractional_scale_v1.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `winit` due to previous error
```

It seems like the `wayland` feature is getting enabled in the `winit` crate, even if not enabled in `eframe`.

(I also tested this using eframe from latest git master, same error)

**To Reproduce**
1. `cargo init`
2. `cargo add eframe`
3. Copy in minimal eframe example from https://docs.rs/eframe/latest/eframe/ to `main.rs`
4. `cargo build --release --target armv7-unknown-linux-musleabihf`

**Expected behavior**
I expected no wayland-related build errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser n/a
 - Version 3.4.90

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Additional context**
n/a

**Comment by RealRTTV** [comment]
Encountering the same issue cross-compiling windows -> aarch linux

**Comment by anushadatar** [comment]
anushadatar@Anushas-MacBook-Air ald_system % vim Cargo.toml
anushadatar@Anushas-MacBook-Air ald_system % cargo check
    Checking epaint v0.23.0
    Checking winit v0.28.7
    Checking postcard v1.0.8
error: couldn't read /Users/anushadatar/github/firmware/apps/ald_system/target/aarch64-unknown-linux-gnu/debug/build/winit-ec78ae2ffea07e6f/out/fractional_scale_v1.rs: No such file or directory (os error 2)
  --> /Users/anushadatar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/protocols.rs:13:1
   |
13 | include!(concat!(env!("OUT_DIR"), "/fractional_scale_v1.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `winit` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
