### ISSUE TITLE
widgets disappear

### ISSUE THREAD

**Issue by askeladd123** [emilk/egui#3264]
When you chain widgets together in an if statement, the widgets behind in the chain disapear. 

This is because I chain them with an `||` operator. If one of the statements is true, the compiler doesn't bother to check the rest. That's why this is really an api flaw, and not a bug.

## reproduce
I used bevy to make an egui window:

```rust
use bevy::prelude::*;
use bevy_egui::{egui, EguiContexts, EguiPlugin};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(EguiPlugin)
        .add_systems(Update, ui_example_system)
        .run();
}

fn ui_example_system(mut contexts: EguiContexts) {
    egui::Window::new("Hello").show(contexts.ctx_mut(), |ui| {
        let mut buf1 = 1;
        let mut buf2 = 1;

        let mut changed = false;

        if ui.add(egui::Slider::new(&mut buf1, 0..=100)).changed()
            || ui.add(egui::Slider::new(&mut buf2, 0..=100)).changed()
        {
            changed = true;
        }
    });
}
```

You can see that if you use the first slider in this example, the second will disappear. This can be fixed by putting each slider in a seperate statement:
```rust
let mut changed = true;

changed |= ui.add(egui::Slider::new(&mut buf1, 0..=100)).changed();
changed |= ui.add(egui::Slider::new(&mut buf2, 0..=100)).changed();
```
While this fixes my problem, it is quite limited.

**Comment by apessino** [comment]
Neither limited nor an API "flaw." egui is an *immediate mode* GUI library and it architected as such - you are not querying sliders that have been defined in data elsewhere and retained, you are actually creating and interacting with the sliders each frame from code, so of course code that does not run does not result in UI. You should start here:

https://en.wikipedia.org/wiki/Immediate_mode_GUI

You should also close this "issue" because it makes no sense.

**Comment by askeladd123** [comment]
I know why it doesn't work. I just think it would be nice if you could have multiple widgets in one _if statement_ the way i described, without them disappearing or flickering. This could be done with something like this:
```rust
if or(ui.add(widget1), ui.add(widget2)).changed() {...}
```
I will of course close the issue if it doesn't make sense. I am new to open source so trying to learn.

**Comment by apessino** [comment]
Learning is good, all I am saying is that it is better to make sure one understands an environment fully before throwing around words like "api flaw."

As for your clarification, the difference between the logical operators `||` and `|` (and `&&` and `&`) is precisely that the latter execute even if the left hand side would have already determined the result of the operation, so just use `|` instead of `||` in your original and your right hand will always execute. You basically already had it at the bottom of your example.

```rust
if ui.add(egui::Slider::new(...)).changed() | ui.add(egui::Slider::new(...).changed() {
    // ...
}
```
