### ISSUE TITLE
egui-wgpu: allow some way to get the surface and/or a texture

### ISSUE THREAD

**Issue by tgross35** [emilk/egui#3369]
**Is your feature request related to a problem? Please describe.**
I am having some issues creating `TextureView`s because they seem to rely on haaving the `Surface`. Reference: https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#render

**Describe the solution you'd like**

A way to get the currrent surface, maybe another field in RenderState?

**Describe alternatives you've considered**

I am just feeling my way through wgpu and there could be a better way to do this. If anyone knows of a way to do something simple like set the background color without the current `TextureView`, please share 🙂 

**Additional context**

**Comment by tgross35** [comment]
@Wumpf it seems like you may be egui-wgpu expert, do you have any suggestions here?

**Comment by Wumpf** [comment]
When you use egui-wgpu together with eframe the surface (and per frame surface texture) is managed by egui-wgpu's winit binding (or on the web by a bit of code inside eframe). Every frame the egui-wgpu renderer creates a renderpass that writes into the current surface texture. Drawing custom content into during this render pass is made possible via the render callback.
Since for the general case one can't access the surface texture other than drawing via a `wgpu::RenderPass` I don't think it makes much sense to expose it directly in this setup. The only other thing one could do with it is create your own `wgpu::RenderPass` that target it, but imho that makes little sense because in that context you don't want to overwrite what egui did so far and the only other meaningful customization beyond that is to add a depth buffer which is exposed already. Unless though ofc you can point out some concrete shortcoming with that :)

There is ofc a different kind of usage pattern where an egui window is on top of your own content. In that case you'd be in charge of drawing egui, but I think in this case use of eframe is a bit more questionable, at least it should be done with a custom renderer then (which in turn may still use egui-wgpu, just don't use the eframe -> egui-wgpu integration).

**Comment by tgross35** [comment]
That makes a lot of sense! I appreciate the thorough explanation
