### ISSUE TITLE
Issue with number key mapping

### ISSUE THREAD

**Issue by mkrueger** [emilk/egui#3415]
Seems I don't get egui::Event::Key events for the number keys when shift is pressed - works with any other modifier.
And shift seems to work with other keys as well, but the numbers:

```
        if ui.input(|i| i.key_pressed(egui::Key::Num1)) {
            print!("1 pressed!");
        }
```

**Comment by YgorSouza** [comment]
The number keys stop being number keys when you hold shift. This is the code that converts the key variants from winit to egui:

https://github.com/emilk/egui/blob/12b6f2c3a0c2c63c2f8b5fc1e320d6d6cea4cc21/crates/egui-winit/src/lib.rs#L773-L862

I put a `dbg!` on the `key` variable, and when holding shift, it sends `At` when pressing 2, `Asterisk` when pressing 8, and nothing for the other keys, because apparently winit doesn't have variants for them either.

**Comment by mkrueger** [comment]
y it's surely not easy. I've worked on editors for 20+ years and my solution was decomposing keys for that. Was always a bit of a mess. But on application level sometimes it's required unfortunately.

There is a conflict between shortcut keys and text input that's not really modelled well on OS level. 


The hacky solution we used for gtk doesn't help here, but shows the way:
https://github.com/mono/monodevelop/blob/main/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs#L485

For solving that you need access to something like that: 
https://docs.gtk.org/gdk3/class.Keymap.html

The raw keys get mapped to real keys let's say shift+1 maps to ! and on app level you get '!' - that needs to be taken back. It's tricky and unfortunately I don't know enough about the VirtualKeyCode thing there to be really helpful.

**Comment by mkrueger** [comment]
0.25 improved key input but I stll don't get a key event for shift+number - only the text event.
