### ISSUE TITLE
Hex string to Color32, Color 32 to hex string

### ISSUE THREAD

**Issue by sdasda7777** [emilk/egui#3466]
**Is your feature request related to a problem? Please describe.**
I have strings in format "#aabbcc" that I would like to convert to Color32, but there apparently isn't a good way to do this. I think it would be useful to provide methods for conversion to and from some similar string format (perhaps without the "#").

**Describe the solution you'd like**
I would like to see Color32 implement some method that would allow for parsing of these hex strings, since it is very much a common format and I do not believe I should be manually writing a parser for hex strings when I want to create a UI.

**Comment by YgorSouza** [comment]
Converting hex strings to colors is already possible via the [hex_color](https://docs.rs/epaint/0.23.0/epaint/macro.hex_color.html) macro, with the caveat that it only works with literal strings, and you have to add the color-hex crate as an explicit dependency due to a bug in the macro, reported in #2644.

Writing your own parsing function is relatively easy by leveraging the u32 parser:

```rs
fn color_from_hex(hex: &str) -> Option<Color32> {
    let hex = hex.trim_start_matches('#');
    let alpha = match hex.len() {
        6 => false,
        8 => true,
        _ => None?,
    };
    u32::from_str_radix(hex, 16)
        .ok()
        .map(|u| if alpha { u } else { u << 8 | 0xff })
        .map(u32::to_be_bytes)
        .map(|[r, g, b, a]| Color32::from_rgba_unmultiplied(r, g, b, a))
}
```

Formatting a color as a hex string is even easier:

```rs
format!("{:08x}", u32::from_be_bytes(color.to_srgba_unmultiplied()));
```

But I suppose egui could provide these methods if there is no ambiguity over what they are supposed to do. This also ties into #3284, so it will probably have to be implemented at some point anyway.

**Comment by sdasda7777** [comment]
Hi, thanks for reply. I am aware of the macro, unfortunately I am working with strings and not literals, so it's not of much use to me. I know the function is not too complicated to write, but I would imagine this is something lot of people use in some capacity, so I think it would be for the best to have it implemented correctly.

**Comment by YgorSouza** [comment]
There is actually a crate that handles all CSS color formats, as part of the servo project: [cssparser-color](https://crates.io/crates/cssparser-color). So maybe `ecolor` could just add it as an optional dependency and `impl From<cssparser_color::Color> for Color32` when it is enabled. I'll try to put together a PR to see how it goes.
