### ISSUE TITLE
Inaccurate Scaling of Widgets in Zoom Feature

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#3728]
Title: Inaccurate Scaling of Widgets in Zoom Feature

Dear Emilk,

When zooming in or out using the zoom feature, widgets are not scaled precisely in proportion to the screen size. As a result, the overall appearance of the screen may change, and widgets at the edges of the screen may become invisible.

In versions like egui v0.22.0 or v0.23.0, the scaling was accurate and proportional. However, in egui versions v0.24.0 and v0.24.1, this issue has been observed.

Thank you,
Emilk.

egui Version: v0.24.0, v0.24.1
Operating System: Windows 10

**Comment by emilk** [comment]
Can you show some screenshots of this?

**Comment by rustbasic** [comment]
Dear Emilk,

I have native_pixel_per_point set to 1.25 on Windows. The screenshots below show configurations of 0.75, 1.00, 1.25, and 1.50. 

In both egui v0.22.0 and egui v0.23.0, changing the pixel_per_point did not affect the appearance of the screen.

Thanks,
Emilk.


![screen075](https://github.com/emilk/egui/assets/127506429/0bfadb2b-4e25-4a39-897e-3f25ef1a1604)
![screen100](https://github.com/emilk/egui/assets/127506429/7f139c57-a080-413a-9e44-3f90817a9454)
![screen125](https://github.com/emilk/egui/assets/127506429/73029b81-8cb8-4458-b4bb-435937b8cbd1)
![screen150](https://github.com/emilk/egui/assets/127506429/374e3346-758c-40d7-a953-14a7086f984a)

**Comment by emilk** [comment]
This is expected behavior - `pixels_per_point` is how many physical pixels wide a logical ui point is.

In normal cases you shouldn't change `pixels_per_point` yourself. Use `Context::set_zoom_factor` to zoom the screen, or don't. `pixels_per_point` will be calculated automatically based on the current zoom factor and the resolution of your monitor.

> In both egui v0.22.0 and egui v0.23.0, changing the pixel_per_point did not affect the appearance of the screen.

That may have been because your egui backend was over-writing it every frame, I don't know. Setting `pixels_per_point` now changes the `zoom_factor`. So basically, it has been fixed so that it now actually work as it should!

**Comment by rustbasic** [comment]
It works fine when I use `ctx.set_zoom_factor()`.
Thanks, emilk.
