### ISSUE TITLE
custom_window_frame : Draging window sometimes goes bad

### ISSUE THREAD

**Issue by 12089897411** [emilk/egui#3791]
**Describe the bug**
Drag Window to another position sometimes bad

**To Reproduce**
1. Run the example 'custom_window_frame'
2. Drag the window bar to another position
3. Repeat step 2 multiple times
4. Seeing the error that the window cannot be dragged

Screenshots
https://github.com/emilk/egui/assets/108512675/d9c72117-4082-4f4a-b0c3-251b7db0d88c

Desktop (please complete the following information):
 - OS: Windows 11
 - Version 25.

**Comment by axxop** [comment]
This bug is only reproducible on Windows, it works fine on Linux.

**Comment by FlyingYu-Z** [comment]
This issue is still not resolved.

Window dragging only works every other attempt — after one drag, you must release and try again before the window can be moved.

I can demonstrate the issue in code:

```rust
if title_bar_response.drag_started_by(PointerButton::Primary) {
    ui.send_viewport_cmd(ViewportCommand::StartDrag);
}

if title_bar_response.drag_stopped() {
    println!("Window drag stopped");
}
```

On Linux (Ubuntu 22.04), releasing the primary mouse button does not immediately trigger `drag_stopped()`.

Instead, "`Window drag stopped`" is printed only when starting the next drag.

This means the drag end event is delayed by one interaction, which explains why window dragging only works every other attempt.

Command used:
`cargo run --release -p custom_window_frame`

Desktop environment:
Ubuntu 22.04
