### ISSUE TITLE
Select text across widgets

### ISSUE THREAD

**Issue by emilk** [emilk/egui#3816]
* Follow-up to https://github.com/emilk/egui/issues/3804 and https://github.com/emilk/egui/pull/3814

Since https://github.com/emilk/egui/pull/3814 we can now select text within a single Label. However, if you put several widgets in a layout, you cannot select all the text across them at once. This gif showcases this shortcoming, here mixing `Label` with `Hyperlink`:

![select-shortcoming](https://github.com/emilk/egui/assets/1148717/331853d4-6c49-46af-90f2-eea7ee079673)

In order to support this we need to keep track of the first and last widget of the selection. During layout, egui needs to track wether or not we are hitting one of these "edge" widgets, and then automatically mark all widgets in between as selected.
When hitting the "copy" button, the text of all widgets needs to be copied.

We should probably only allow drag-to-select a range within the same _layer_ (i.e. Window/Area).

### Copying text
When hitting `Cmd C`, each fully or partially selected widget needs to _append_ their text to the clipboard, and probably insert an extra space between (unless there already is one).

Handling this in the general case of right-to-left layouts will be difficult, so let's start with simple left-to-rigth/top-down layouts first.

**Comment by juancampa** [comment]
@emilk this is amazing, I have a lot of `TextEdit` in my code and string concatenation just to get selection. Very happy that you're working on this.

I figured that since you're actively working on this you might wanna tackle this inconsistency with the cursor to bring it closer to how text works.

https://github.com/emilk/egui/assets/1410520/39d850f5-1378-42b9-97a3-8d7d7ea76d6f

Basically, the cursor should become `CursorIcon::Text` while hovering actual text, not the bounding box. Hopefully this can be implemented with [Galley::cursor_from_pos](https://docs.rs/egui/latest/egui/struct.Galley.html#method.cursor_from_pos) but I'm not sure.

**Comment by juancampa** [comment]
> cursor should become `CursorIcon::Text` while hovering actual text, not the bounding box

Awesome! Seems like this was indeed fixed in this PR 🥳
