### ISSUE TITLE
Windows cannot be resized when in front of a plot

### ISSUE THREAD

**Issue by s-nie** [emilk/egui#3923]
Happens on the current master branch: 527f4bfdf69f1ae2eb204258f872cfc2da20433f

Windows cannot be resized by dragging the bottom right corner when they are in front of a plot. The corner just jumps away.

@emilk Do you have a suspicion where the issue might come from? I'd be happy to try and fix it.

In the web demo it looks like this:

https://github.com/emilk/egui/assets/73159570/f24fe0d2-86c3-4715-a71d-679398f90503

**Comment by YgorSouza** [comment]
I've made the following observations, if it helps:

- It has nothing to do with the plot specifically. It happens with anything that senses the drag event, like selectable text or a slider. It does not happen with non-draggable things like buttons.
- Not every window is affected. For example, in the demo app, the settings window and the table demo window don't have the problem. But all the windows do that little jump when you click on the resize handle.
- It only happens if the handle is above a draggable widget when you first click on it. Dragging the handle on top of something after you've clicked on it does not cause problems.

I'll try to bisect and find out when it started.

**Comment by YgorSouza** [comment]
It seems that it started with #3515.

**Comment by emilk** [comment]
The interaction code could use some cleanup. I think the problem can be solved with:
* https://github.com/emilk/egui/issues/3936

**Comment by s-nie** [comment]
Thanks for opening an issue! I was hoping that this would be something that the plot itself does not handle properly. Unfortunately I don't have the capacity to delve deep into the interaction code at the moment.
