### ISSUE TITLE
Do all widget interaction at the start of the frame

### ISSUE THREAD

**Issue by emilk** [emilk/egui#3936]
`Context` uses `WidgetRects` to store the rectangles of all widgets from the previous frame. `Context::interact` uses this to check that no tother widget is covering the current widget.

This code could be simplified by doing the hit-test once at the _start_ of the frame, using the `WidgetRects` from the previous frame.

With full knowledge, we could to a smart hit-test where we look for all widget within a certain small radius of the pointer, and hover/click/drag the closest one. This allows for slightly bigger hit-boxes, making things easier to click. This could replace the current hack of growing hit boxes by `item_spacing / 2`.

Note that we needs to find the top widget for clicks and for drags separately, because the top widget that is click-sensitive (e.g. a button) can be different from the top widget that is drag-sensitive (e.g. a ScrollArea).

**Comment by abey79** [comment]
Side note for drag-sensitive areas, in the context of e.g. hierarchical list (as in #3903). It's rather important that the drop zone be exactly contiguous. Otherwise, this could introduce a discontinuity when the mouse moves from the bottom of a widget to the top of the next one, with the insertion marker disappearing and the drop potentially failing.

![Export-1706807772224](https://github.com/emilk/egui/assets/49431240/b7826196-2c00-4f8f-b0f7-f0d241d3137b)

Here are the drop zones for this example:

<img width="587" alt="image" src="https://github.com/emilk/egui/assets/49431240/b8281116-6a24-4895-bfed-888c5a5e0c90">

This is easy to achieve with custom widget and `item_spacing = 0`, as the `response.rect` are already that way. It's slightly less convenient with non-zero spacing.

**Comment by emilk** [comment]
I just realized this is going to make styling a lot easier, since we know before adding a widget wether or not it is hovered, dragged etc, which means we can pick its colors (and margins) based on ints interaction state before allocating space for the widget!

This makes this issue an important part of:
* #3284
