### ISSUE TITLE
Intermediate compatibility layer API

### ISSUE THREAD

**Issue by kvark** [emilk/egui#4202]
**Is your feature request related to a problem? Please describe.**
As an engine developer, I'm feeling very concerned about depending on a library with version 0.26. It tells me that the library is progressing faster than my engine, and so I'm left with the choice of either:
  1. not exposing egui-related API at all
  2. forced to update with every egui release (at higher frequency than I want)
  3. force the users to stay on older egui when behind

**Describe the solution you'd like**
Perhaps we can put all of the intermediate things into a layer that doesn't change? Specifically:
- `Ui`
- `ClippedPrimitive`
- `TexturesDelta`

Something like [mint](https://github.com/kvark/mint) but for (e)GUI.

**Describe alternatives you've considered**
(posted above)

**Additional context**
I'm integrating support for `cargo-check-external-types` to https://github.com/kvark/blade and seeing this dependency concerning.

**Comment by emilk** [comment]
I want to ship feature of egui often so that people can get to use new stuff right away, and not have to wait. But that doesn't mean every egui user needs to update to every new version of egui. If your engine is using an older version of egui - so what? Your engines users will have to wait to use the latest egui then 🤷  That would be the same effect as me slowing down the release schedule.
