### ISSUE TITLE
TextEdit partially ignore clicks when they are not centred enough

### ISSUE THREAD

**Issue by abey79** [emilk/egui#4206]
I noticed that text edit will react, but _not_ activate text cursor, when clicked near its margin. When the click is well centred, the text edit activates properly.

Repro on `master` as of now, with the stock `hello_world` example. Notice how the text cursor shortly appears and immediately disappear after each click, until the last click that occurs closer to the centre:

https://github.com/emilk/egui/assets/49431240/c2d4595b-81f3-48f6-bca9-24f4b4053978

**Comment by YgorSouza** [comment]
That seems to be caused by this block:

https://github.com/emilk/egui/blob/769199648db30dadbec21cd1845bc325c5c91024/crates/egui/src/widgets/text_edit/builder.rs#L396-L398

If I remove the `&& !output.response.lost_focus()`, it seems to work correctly. But I don't know why this condition is there in the first place.

There is this other block that gets focus on pointer down instead of click.

https://github.com/emilk/egui/blob/769199648db30dadbec21cd1845bc325c5c91024/crates/egui/src/widgets/text_edit/builder.rs#L563-L565

So it seems that when you click near the edge, the response's `clicked_elsewhere` is true and it surrenders focus immediately, so the first block does not acquire focus.

**Comment by rustbasic** [comment]
This appears to be intended behavior.
It appears to be so that other functions can be added.
Hold the click for about 0.3 seconds to get focus.

**Comment by crumblingstatue** [comment]
> Is this intended behavior?

I hope it's not intended, because I thought there is something wrong with my system or egui when my text input kept getting unfocused.

**Comment by rustbasic** [comment]
It is inconvenient because the recognition range is narrow.
I think it would be good to broaden the scope of awareness.
