### ISSUE TITLE
Central panel ignores second top panel

### ISSUE THREAD

**Issue by nmlt** [emilk/egui#421]
**Describe the bug**
If you add a second top panel to the central panel, the content of the central panel begins inside this top panel. Depending on whether the top panel is the first thing inside the central panel or not, either the rest of the central panel is covered or the top panel is covered.

**To Reproduce**
Using the egui-template repository, copy this code into the `CentralPanel::default().show()` function:
```
egui::TopPanel::top("top_panel").show(ctx, |ui| {
      ui.label("example");
});
```

**Expected behavior**
UI elements in the central panel respect the boundaries of another top panel and aren't rendered on top of or behind it.

**Screenshots**
![egui-top-panel-covered](https://user-images.githubusercontent.com/12828175/118966877-55acec00-b96a-11eb-93a7-aef2239f9138.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux with Gnome 40.1

As it works without a problem (except this), I expect adding multiple top panels to be allowed. But of course one could also simply use a `horizontal` and `separator` afterwards.

Also, great work with egui! Thanks!

**Comment by emilk** [comment]
This is expected behavior. As [the docs for `CentralPanel`](https://docs.rs/egui/0.12.0/egui/containers/struct.CentralPanel.html) states, it must be added *last* after all other panels. Adding panels from within panels is also not allowed (and will panic if you compile `egui` with the new `extra_asserts` feature flag)
