### ISSUE TITLE
Blurry font rendering in firefox on linux

### ISSUE THREAD

**Issue by mash-graz** [emilk/egui#4241]
Although some older similar issue reports exist, I want to document the `egui` Web rendering differences on firefox vs. chromium on my debian linux gnome wayland machine.

The differences are rather subtle and hard to grasp, but they make it very uncomfortable to work with text in `egui` in browser based applications.

I attach a view example screenshots:

![chromium](https://github.com/emilk/egui/assets/13013641/6db909ce-3277-4428-8922-736358d26a4e)
![chromium2](https://github.com/emilk/egui/assets/13013641/1abf1bf2-290c-4f14-b272-6b1d8942d7a8)
![firefox](https://github.com/emilk/egui/assets/13013641/684a096b-50a1-47b9-99d6-a1f15f779703)
![firefox2](https://github.com/emilk/egui/assets/13013641/add49c37-e766-4e6e-babd-5fc7feb6c7b9)
![side-by-side](https://github.com/emilk/egui/assets/13013641/2cc66e59-0df2-41f2-a9df-9e23be14fc4f)

**Comment by lnicola** [comment]
Same for me, if not worse:

![image](https://github.com/emilk/egui/assets/308347/5bd65c11-defe-437e-81f0-251030e49da5)

Bad gamma, maybe?

**Comment by CryZe** [comment]
@lnicola That's how it's supposed to look. It's just that the default text color is grey, not black and that the text hinting is not particularly great (if it even exists).

**Comment by emilk** [comment]
The problem is that egui's pixel grid is not aligned with the pixel grid of the display:

Firefox:
<img width="739" alt="Screenshot 2024-03-27 at 15 31 18" src="https://github.com/emilk/egui/assets/1148717/22c80335-437d-43e4-96b3-794c5782a0a8">

In Chromium it is better, but it is still wrong vertically:
<img width="501" alt="Screenshot 2024-03-27 at 15 32 13" src="https://github.com/emilk/egui/assets/1148717/296b15b6-1034-4dda-8977-c0d942077167">

(these are blow-ups of your screenshots).

Is suspect we can fix it by tweaking how the canvas element is aligned in its parent somewhere in
https://github.com/emilk/egui/blob/a15e6c21220e593932569558a31de9403e3791d0/crates/eframe/src/web/mod.rs#L127-L130

**Comment by emilk** [comment]
I can reproduce this on chromium on my Mac now, so I'm taking a look

**Comment by emilk** [comment]
It looks like it is the rounding-to-even added in https://github.com/emilk/egui/pull/151 that is causing the problem. Removing that makes the rendering pixel-perfect on Firefox and Chromium (on my Mac), but Safari is still blurry on most zoom levels.

**Comment by emilk** [comment]
Please help test if https://github.com/emilk/egui/pull/4299 fixes your problem!
