### ISSUE TITLE
Better tooltip size management

### ISSUE THREAD

**Issue by emilk** [emilk/egui#4471]
Similar issues:
* https://github.com/emilk/egui/issues/3974
* https://github.com/emilk/egui/issues/4452

Tooltips sometimes flicker the first time they show up.
This is because we don't know their size before we show them, and their size affects their position.

I think we should hide the tooltips for the first frame, and use that only for sizing calculations.
Once calculated, we store the size for use the subsequent frames.
The tooltips size will be assumed to be constant during its lifetime.
Once a tooltip is hidden, we forget about its size.

This will also allow for better sizing within a tooltip: a user will be able to add "full width" widgets (such as `Separator`) that are only as wide as the widest element.

**Comment by abey79** [comment]
This PR is good test case because the tooltip has two sources of flicker:
- needs to move above the cursor because there isn't enough room bellow
- the component list takes 2 frame to be sized correctly

https://github.com/rerun-io/rerun/pull/6309

https://github.com/emilk/egui/assets/49431240/23f34b93-3d56-49c9-9c09-ec08b721d41d

**Comment by emilk** [comment]
Probably closed by https://github.com/emilk/egui/pull/4579 but should be tested with https://github.com/rerun-io/rerun/pull/6309 first

**Comment by emilk** [comment]
Yup, tooltips feel great now!
