### ISSUE TITLE
Grid layout for windows

### ISSUE THREAD

**Issue by andreamancuso** [emilk/egui#4550]
I am not 100% convinced this currently achievable in egui: https://github.com/react-grid-layout/react-grid-layout

If it is, could you please point me to a demo/example code?

If not, are there plans to build something along these lines?

I am aware of https://github.com/Adanos020/egui_dock https://github.com/rerun-io/egui_tiles and https://github.com/rerun-io/egui_tiles/issues/30 but they don't quite seem to support the react-grid-layout use case(s)

Thanks!

**Comment by YgorSouza** [comment]
I have a feeling this would fall under the [non-goals](https://github.com/emilk/egui#non-goals):

> Advanced and flexible layouts (that's fundamentally incompatible with immediate mode)

But I'm not sure. In any case, egui_dock and egui_tiles are indeed the closest we have to that at the moment.

**Comment by andreamancuso** [comment]
Thanks for confirming!

I see the official egui online demo includes a button for reorganising the currently open windows so they are redistributed evenly across the available space. Are there other "strategies" documented anywhere?

**Comment by YgorSouza** [comment]
The code run when you click on this button is this:

https://github.com/emilk/egui/blob/942fe4ab314323a66077fece4655c6e8e8c810a8/crates/egui_demo_lib/src/demo/demo_app_windows.rs#L309-L311

https://github.com/emilk/egui/blob/942fe4ab314323a66077fece4655c6e8e8c810a8/crates/egui/src/memory.rs#L842-L848

So it just forgets the previous data about all the windows, and because they already look for empty space when determining their initial position, this has the effect of "organizing" them.

Actually, there is also [egui_dnd](https://crates.io/crates/egui_dnd) which allows you to reorder list items by dragging them, and includes some animations as they move to their new positions. It's still not the same as a flexible layout, though. I don't know if there is anything that gets closer, but you can look in <https://github.com/emilk/egui/wiki/3rd-party-egui-crates>
