### ISSUE TITLE
When two widgets are overlapped, the lower widget receives interaction instead of the top one

### ISSUE THREAD

**Issue by bachdx96** [emilk/egui#459]
As the title suggests, I'm having two widgets which can sometime overlap each other. The first widget is rendered first so it will receive the interaction, but since the second widget is rendered later it will appear on top of the first widget.

This can be replicated in the demo in the Manual Layout Test section. Use the sliders position the button so that the button overlap on top of the sliders. When clicked at the position where the slider is underneath, the event went under the button and received by the slider.

**Comment by emilk** [comment]
This is really hard to fix in an immediate mode GUI.

egui handles this for widgets in different `Area`:s (windows), but within a Ui widgets are expected not to overlap.

**Comment by shanemmattner** [comment]
I ran into this problem and found that the [panels documentation](https://docs.rs/egui/latest/egui/containers/panel/index.html) addresses this issue and how to solve it :

> The order in which you add panels matter! The first panel you add will always be the outermost, and the last you add will always be the innermost.
>
>You must never open one top-level panel from within another panel. Add one panel, then the next.
>
>⚠ Always add any [CentralPanel](https://docs.rs/egui/latest/egui/containers/panel/struct.CentralPanel.html) last.

**Comment by hydra** [comment]
this bug still exists as of egui 0.36.0, I don't know why this was closed as it's unexpected behavior.

there is workaround, you can create an 'input shield' under the widget that you want to appear on top.

it feels to me like this probably could and should be handled by egui itself.

I had the exact same issue in my egui_tool_windows crate, the solution there was to call `ui.interact` before drawing the widgets where the `rect` used by the interact is the same as the one used by a new `Ui` into which the controls are drawn.

```
let rect = ....; // precalulate where the later control will render.

let shield_response = ui.interact(rect, self.id.with("__tool_window_shield"), Sense::click_and_drag());
```

I then created a `ui` using `Ui::new()` with the same `rect` and rendered what it needed to inside that.

Prior to this I had 'bleed-though' of hover and drag events to obscured widgets, just like in this video I made using egui 0.36.

https://github.com/user-attachments/assets/928fe064-c259-47a4-8cee-674cd6e09c79

Source for my crate which has this workaround is here:

https://github.com/MakerPnP/egui_tool_windows/blob/master/src/tool_windows/mod.rs

This doesn't fix the underlying issue, which still needs to be fixed in egui.
