### ISSUE TITLE
`DragValue` with `min_decimals` set to 1 formats `0.0` as `0`

### ISSUE THREAD

**Issue by Skgland** [emilk/egui#4610]
**Describe the bug**
With `min_decimals` set to one all values should be displayed with at least one decimal,
but `0` is displayed instead of `0.0`

**To Reproduce**
Create a UI containing a `DragValue` with min_decimals set to 1 and with a current value of 0.0.
e.g. 
`ui.add(egui::DragValue::new(&mut 0.0).min_decimals(1))`

**Expected behavior**
`min_decimals` is honored and `0.0` is displayed.

**Screenshots**

![image](https://github.com/emilk/egui/assets/3877590/225910ff-899b-40e8-80e0-aef993a8eb19)

**Desktop (please complete the following information):**
 - OS: Ubuntu Jammy 22.04 under WSL 2/ Debian Bullseye
 - Version `0.25.0`

**Additional context**

This is probably due to this special case:
<https://github.com/emilk/egui/blob/master/crates/egui/src/widgets/drag_value.rs#L456-L458>

**Comment by YgorSouza** [comment]
It looks like this special case was added in https://github.com/emilk/egui/commit/ebc2486d22355eb6ef1f4827f4304210969b60eb#diff-3878bfa9f60333dd78982f3697643c6755ff8378f18b54fff03973c1eff5fcc8L159-R173 more than 3 years ago, and kept this way ever since. But I don't know what is the reasoning behind it.
