### ISSUE TITLE
Nicer looking text selection in light mode

### ISSUE THREAD

**Issue by emilk** [emilk/egui#4727]
When selecting text, we draw the selection _on top_ of the text. This limits how we can do nice highlighting. This is most notable in the light mode of egui.

We should instead show the selection as a changed background color, keeping the text color the same.

**Comment by YgorSouza** [comment]
What should be done when the text already has a background color? There is actually a note about that in the code.

https://github.com/emilk/egui/blob/d4e8966aac9347965f8d02310ecf2c9f23bb9bbc/crates/egui/src/text_selection/label_text_selection.rs#L24-L33

If we just switch the order of the text and the selection highlight, the background makes it impossible to see that the text is selected.

![image](https://github.com/emilk/egui/assets/43298013/0b20acbb-cf8e-42ea-b3b3-2ff158a6d88a)

![image](https://github.com/emilk/egui/assets/43298013/78612dce-9a16-43b4-a693-9f24bc56c1c2)


So I guess when there is a selection, the text would have to be painted twice? First with a transparent foreground, and then with a transparent background, so the highlight can be sandwiched in the middle. Or would it be a matter of overriding the `LayoutSection`s in the galley to put the highlight background where it needs to be?

**Comment by YgorSouza** [comment]
Another option could be to change `expand` to `shrink` here:

https://github.com/emilk/egui/blob/d4e8966aac9347965f8d02310ecf2c9f23bb9bbc/crates/epaint/src/text/text_layout.rs#L744-L750

![image](https://github.com/emilk/egui/assets/43298013/1c12b45f-5bf9-4039-98c8-646c50697b06)

But it doesn't look great, depending on the characters. Maybe expand on X and shrink on Y?

![image](https://github.com/emilk/egui/assets/43298013/81282b52-7213-4aaf-ba94-cbcc00945c65)


I guess "show the selection as a changed background color" means putting the selection information in the `LayoutJob`, so it can be added to the mesh in the function linked above. But that would mess with the memoization and potentially make the UI slower when the selection is changed. Also, the user can pass a finished `Galley` to the `Label`, so it would not be possible to change it to add the selection.

https://github.com/emilk/egui/blob/d4e8966aac9347965f8d02310ecf2c9f23bb9bbc/crates/egui/src/widgets/label.rs#L134-L137

**Comment by emilk** [comment]
It's a good analysis @YgorSouza!

One option is to let `Label` modify the generated `Galley`, to replace any background in it and add the new selection as a background. It will still require some work, but feels doable. I would probably do it like this:

For each `Row` with a selection, generate two new triangles (=selection rectangle) and add it to `RowVisuals` mesh. The vertices can just be appended to the back, and the triangle indices should be inserted after the original background triangles (if any), but before the triangles of the actual glyphs. This means `RowVisuals` would need to have a new field to keep track of the first triangle index with a glyph (usually zero in case of no backgrounds).

**Comment by YgorSouza** [comment]
The `RowVisuals` already stores the range of vertices corresponding to glyphs, so technically we could just do a linear search to find the first triangle with vertices in that range. It should be fast most of the time, unless you have lots of backgrounds in the row.

https://github.com/emilk/egui/blob/31716d787e7fc43bf5626c1c0692d8ad347d246d/crates/epaint/src/text/text_layout_types.rs#L557-L560

The downside of this method is that since the `Galley` is passed around in an `Arc`, it would usually have to be cloned in order to be mutated. But I guess the only way to avoid that would be to completely split off the background into a separate mesh, and then modify `TextShape` with an option to paint only the background, or only the foreground.

Then again, the `Galley` is already cloned here when transforming the shape, so maybe it's fine to clone it for the selection as well.

https://github.com/emilk/egui/blob/31716d787e7fc43bf5626c1c0692d8ad347d246d/crates/epaint/src/shape.rs#L434-L444
