### ISSUE TITLE
String input to Float Conversion in TextEdit Widget

### ISSUE THREAD

**Issue by Shrav108** [emilk/egui#4887]
I am trying to create an application for an engineering project. I want to know how to convert the string input (from TextEdit Widget) from the user to a floating value.

Currently, my struct fields are 'String' type. I later parse it to float using pattern matching.

```
struct HydroStatic{
    pressure      : String,   // There are few more fields
}
```
Taking Input from user as String in TextEdit Widget
` ui.add(egui::TextEdit::singleline(&mut self.pressure));`

What I would like to do is : 
```
struct HydroStatic{
    pressure      : f64,   // There are few more fields
}
```
I would like to some how implicitly convert to f64 in this line : 
` ui.add(egui::TextEdit::singleline(&mut self.pressure)); // String to f64 implicit conversion ?`

Is there a way to do it ?  
Does it involve any trait implementation ?

**Comment by YgorSouza** [comment]
You can use the [DragValue](https://docs.rs/egui/0.28.1/egui/widgets/struct.DragValue.html) instead.

**Comment by Shrav108** [comment]
Thank you ! This works for me.

But I was wondering how to convert the TextBuffer in TextEdit to f64 ?  Is there any trait implementation on TextBuffer ?

**Comment by YgorSouza** [comment]
The `DragValue` itself does it like this:

https://github.com/emilk/egui/blob/64d5f948e43b4be93e3a4541c87dcce74c948df4/crates/egui/src/widgets/drag_value.rs#L687-L697

You can do that if you want, but the problem is that while the user is typing, if they temporarily type something that does not convert properly to f64, you would overwrite what they typed, which is a bad user experience. So you would also have to store the string somewhere between frames, and only change it when the user is done typing, which the `DragValue` does like this (among other places):

https://github.com/emilk/egui/blob/64d5f948e43b4be93e3a4541c87dcce74c948df4/crates/egui/src/widgets/drag_value.rs#L512-L514

**Comment by Shrav108** [comment]
Thank you. I think drag value is better for my application.
