### ISSUE TITLE
Frame demo ID clash

### ISSUE THREAD

**Issue by Swarkin** [emilk/egui#4965]
**Describe the bug**
![image](https://github.com/user-attachments/assets/ff5261ef-1034-4c97-94e2-8f8d5fc072a4)

**To Reproduce**
1. https://www.egui.rs/
2. Enable `Frame` demo
3. Disable the first two "same" checkboxes

**Comment by YgorSouza** [comment]
As the web demo is built in release mode, the ID clash warning is off by default. It can be toggled in the settings, and it is turned on when you open the ID Test window. That's why you may or may not see the warning depending on what you clicked on.

https://github.com/emilk/egui/blob/1f6ae49a5f6bf43a869c215dea0d3028be8d742a/crates/egui_demo_lib/src/demo/tests/id_test.rs#L19-L20
