### ISSUE TITLE
[Proposal] `settings_ui()` recommended to remove `#[cfg(debug_assertions)]`.

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#5222]
[Proposal] `settings_ui()` recommended to remove `#[cfg(debug_assertions)]`.

It's recommended to remove `#[cfg(debug_assertions)]` in files like style.rs, context.rs, and pass_state.rs.

Beyond the level of example programs, if a release is not performed, stack overflows may occur, making program execution difficult.

Therefore, if `#[cfg(debug_assertions)]` is not removed, the Debug function in settings_ui() cannot be used. 

In my opinion, the drawbacks of removing `#[cfg(debug_assertions)]` are minimal.

**Comment by lucasmerlin** [comment]
Why would `#[cfg(debug_assertions)]` cause a stack overflow?

**Comment by rustbasic** [comment]
> Why would `#[cfg(debug_assertions)]` cause a stack overflow?

`#[cfg(debug_assertions)]` does not cause stack overflow, but sometimes stack overflow occurs when run a large program without `--release` it.

**Comment by lucasmerlin** [comment]
So have you tried whether actually removing the debug_assertions makes a difference? My guess would be that it isn't related to debug_assertions at all but rather if you run it with --release some optimizations are applied that prevent / delay the stackoverflow. 

I've also had a problem with a stackoverflow and it is fixed by this https://github.com/emilk/egui/pull/5212, so also make sure that this isn't your problem as well.

I'll close the issue because I don't think removing `#[cfg(debug_assertions)]` makes sense.
