### ISSUE TITLE
Color spaces

### ISSUE THREAD

**Issue by parasyte** [emilk/egui#523]
This is going to be a horrible topic, but it has to be done.

Here's a screenshot from the latest demo app color test (`egui_glium`):

![egui-color-space](https://user-images.githubusercontent.com/456942/123529700-d072d080-d6a7-11eb-8317-2e3284c5d99d.png)

Shockingly, the "WRONG" gradient for `transparent..white` on a black background is _perceptually correct_ while the rest of the gradients are completely incorrect. In other words, this gradient is simply outputting every grey from 0 to 255 in sRGB. The others put mid-grey (`sRGB(128, 128, 128)`) at about 22% of the gradient width.

On a side note, it's worrisome is that `egui` is using `Color32` for its internal color representation, almost everywhere. For instance, the vertex colors: https://github.com/emilk/egui/blob/4f6dac27e694237d33e25d49e650e6b871e17a33/epaint/src/mesh.rs#L19-L20

This in turn means that to do any kind of blending, these colors need to be converted to linear space, and then converted back to sRGB for display. All of these conversions mean that color accuracy becomes a problem.

Back to the point. The black/white gradients are clearly showing linearity in terms of emitted light intensity, rather than perceptual light intensity. The difference between the two is better described here: http://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/#light-emission-vs-perceptual-brightness

But this can also easily be checked with a color picker; The grey at the center of most of these gradients is about `sRGB(188, 188, 188)`, which is roughly the same amount of light emitted from two adjacent pixels where one is pure black and the other is pure white (on an sRGB display; more or less every display that matters). It is _not_ the "middle grey" that we think of as _looking like_ it is half way between black and white; that would be `sRGB(128, 128, 128)`.

There is another great description of this problem on Minute Physics: https://youtu.be/LKnqECcg6Gw

**Comment by parasyte** [comment]
In terms of computing the gradients themselves, one should not interpolate the linear color space and simply convert these colors to sRGB, since this creates incorrect results in the greyscales with respect to human visual perception. The gradients should be created with intensity awareness, e.g. as described by [Mark Ransom](https://stackoverflow.com/questions/22607043/color-gradient-algorithm/49321304#49321304).

> The intensity of the gradient must be constant in a perceptual color space or it will look unnaturally dark or light at points in the gradient. You can see this easily in a gradient based on simple interpolation of the sRGB values, particularly the red-green gradient is too dark in the middle. Using interpolation on linear values rather than gamma-corrected values makes the red-green gradient better, but **at the expense of the back-white gradient**. By separating the light intensities from the color you can get the best of both worlds.

(Emphasis is my own)

The empirically determined gamma of 0.43, as far as I am aware, was initially described in [Derivation and modelling hue uniformity and development of the IPT color space](https://scholarworks.rit.edu/theses/2858/).

**Comment by emilk** [comment]
There are many ways to do perceptually uniform color blending, some more advanced than others. Pick the one you prefer! When creating a gradient to show to the user, do not create the two extremes and ask egui to interpolate between them - instead create the gradient you want and pass it to egui. This is for instance what the color picker does to get a perceptually even black-white gradient:

<img width="303" alt="gradient" src="https://user-images.githubusercontent.com/1148717/124644281-61109400-de92-11eb-89aa-52fe85ce5455.png">

egui uses the GPU to sample textures, and when doing billinear/trillinear filtering there are really only two choices: either gamma-space, or in linear space (by using e.g. `GL_SRGB8_ALPHA8`). Out of the two, linear space is the better choice.

When doing compositing in the GPU (blending layers on top of each other) you again only have the choice between gamma space and linear space (and not even than in WebGL, which has caused much headache).

Out of the two, I believe linear blending to be the better and (mathematically) simpler choice, so that is what the reference egui_glium renderer uses.

The color tests shows extreme examples of blending two texels and two vertex colors. If you want finer control for your app: add more texels to your texture and more vertices to your mesh.

I don't see any actionable suggestion here, so I will close this issue. If you have a concrete suggestion (e.g. how and why to implements "Mark's method" to do alpha compositioning in WebGL) please open a separate issue, or repopen this one.

**Comment by emilk** [comment]
> On a side note, it's worrisome is that `egui` is using `Color32` for its internal color representation, almost everywhere

Yes, I have thought about this too. I am considering changing this to `RGBA` everywhere. It might cause some performance regressions (more data to send to the GPU each frame), thought I doubt it.

**Comment by emilk** [comment]
PR: you might be interested in https://bottosson.github.io/posts/oklab/

**Comment by parasyte** [comment]
> Yes, I have thought about this too. I am considering changing this to `RGBA` everywhere. It might cause some performance regressions (more data to send to the GPU each frame), thought I doubt it.

I suspect CPU resources with color format conversions are going to be more expensive than GPU memory bandwidth from such a change. Just a hunch, but it's based on the observation that using `Color32` internally requires writing code like these examples for any kind of processing/animation, etc.

https://github.com/emilk/egui/blob/7c5a2d60c5d000f193bc7b16c5a53c059fee8259/egui/src/widgets/progress_bar.rs#L97

https://github.com/emilk/egui/blob/7c5a2d60c5d000f193bc7b16c5a53c059fee8259/egui/src/widgets/plot/items.rs#L801-L806
