### ISSUE TITLE
ScrollArea is not displaying after upgrade to eframe 13.1

### ISSUE THREAD

**Issue by etrombly** [emilk/egui#530]
I have a scrollArea containing a TextEdit::multiline, it was displaying correctly in eframe 12. If I comment out the scrollArea the textEdit displays correctly. I also tested with auto_sized instead of from_max_height. The behavior was the same.

    egui::CentralPanel::default().show(ctx, |ui| {
        //egui::containers::ScrollArea::from_max_height(f32::INFINITY).show(ui, |ui| {
            let text_edit = egui::TextEdit::multiline(&mut self.text).lock_focus(true);
            let id = egui::Id::new("text_edit");
            let text_edit = text_edit.id(id);

            ui.add_sized(ui.available_size(), text_edit);
        //});
    });

**Comment by parasyte** [comment]
FWIW, it works with `ui.add(text_edit);`

`git bisect` shows the breaking change was 2f46c975a578fbffdf74139102d75b4d3af5d2a2

The default alignment changed to center widgets in the layout vertically. You are requesting that the `text_edit` is added to an area with infinite height (because that's what `ScrollArea` always has). Mathematically, there is no center of infinity.

_It is not possible to adjust how layouts vertically align content (all of them use center-alignment, and there is no method to change it)_. I think this is definitely an oversight and should be fixed.

However, you can capture the available size of the center panel and use that instead of the `ScrollArea` size to make this work right now:

```rust
egui::CentralPanel::default().show(ctx, |ui| {
    let panel_size = ui.available_size();
    egui::containers::ScrollArea::from_max_height(f32::INFINITY).show(ui, |ui| {
        let text_edit = egui::TextEdit::multiline(&mut self.text).lock_focus(true);
        let id = egui::Id::new("text_edit");
        let text_edit = text_edit.id(id);

        ui.add_sized(panel_size, text_edit);
    });
});
```

**Comment by etrombly** [comment]
That worked for me.  Not sure if you want to keep the issue open to track a more permanent fix, but I'm good with this workaround. Thanks for the help.

**Comment by parasyte** [comment]
I believe it is worth addressing the gap with specifying vertical alignment in layouts. This can be as good a tracking ticket as any, IMHO.

**Comment by emilk** [comment]
As @parasyte points out, the available size within a `ScrollArea` is infinite in the y direction (because we can always scroll more). So the problem here is that you are trying to create an infinite TextEdit, which is something you shouldn't do. If it worked before, it probably did so out of accident. It is better to create a finite `TextEdit` and let it expand as more lines are added to it (which it will).
