### ISSUE TITLE
key_pressed is true for 2 frames

### ISSUE THREAD

**Issue by SUPERCILEX** [emilk/egui#5509]
Traced it back to winit: https://github.com/rust-windowing/winit/issues/4048

**Comment by SUPERCILEX** [comment]
Re-opening because this might be something that needs handling on the egui side.

**Comment by John-Nagle** [comment]
I'm seeing this on text input. I can't log into my program because, when I type the user name, each letter is duplicated. So is backspace. 

But my other GUI test program does not have this problem. Checking versions on everything now.

Fails (Sharpview metaverse client):
- egui 0.30.0
- winit 0.30.6

Works (GUI test program ui-mock): 
- egui 0.30.0
- winit 0.30.5

Hm.

**Comment by John-Nagle** [comment]
Rebuilt ui-mock after a "cargo update", so it now uses winit 0.30.6. It now fails, duplicating each character on input.
So something changed between winit 0.30.5 and 0.30.6

Reproduce by:

```
https://github.com/John-Nagle/ui-mock.git
cd ui-mock
git checkout wgpu23safe
cargo build --release --examples
cd target/release/examples
./ui-mock
```
