### ISSUE TITLE
Q: access to ScrollArea offset from top

### ISSUE THREAD

**Issue by ivanceras** [emilk/egui#556]
I have a component that needs to align to the Scrolled position of a TextEdit inside of a ScrollArea. Is there a way of accessing the scroll state of the ScrollArea?

**Comment by parasyte** [comment]
You can use the [`show_viewport()`](https://docs.rs/egui/0.13.1/egui/containers/struct.ScrollArea.html#method.show_viewport) method (available since `0.13.0`), which provides a viewport `Rect` to the closure. The `min.y` value of the Rect is the scroll offset.

BTW, it's better etiquette to ask questions on the [discussions page](https://github.com/emilk/egui/discussions) instead of creating an issue.

**Comment by ivanceras** [comment]
Thank you @parasyte

**Comment by ivanceras** [comment]
I didn't notice there is a discussion page for github repo. I have no idea there is such feature in github at all.
