### ISSUE TITLE
initial_window_size does not work when persistence is enabled.

### ISSUE THREAD

**Issue by sourcebox** [emilk/egui#591]
When persistence is enabled, the main window size is always set to the values stored previously. This is bad in some situations, e.g. when the layout of the application changes.

What I like to do is:
- Set a fixed window size regardless of any stored value
- Provide the user to reset the window size and position to a default state

I already tried `*ui.ctx().memory() = Default::default()` and `ui.ctx().memory().reset_areas()`without success.

**Comment by emilk** [comment]
what do you mean by "main window"? the native window or `egui::Window`? I assume yes, since `ui.ctx().memory().reset_areas()` resets all `egui::Window`. Note that `egui` doesn't have any control or knowledge of the native window.

Since https://github.com/emilk/egui/pull/753 you can turn off peristence of the native window with `App::persist_native_window` (see https://github.com/emilk/egui/pull/753/commits/6cc793265e65d34cfec3e80a68452356cad57762) so i will consider this fixed!

**Comment by sourcebox** [comment]
I'll try to explain the scenario:
- I release version 1 of my app. This has a fixed windows size, but the user should be able to move it around and the position should be remained on next launch.
- I update my app to version 2 and release it. The new version requires a different window size due to some layout changes.
- When the user now opens the new version, the window size for version 1 is restored, leading to a defective layout.

So my request is that the native window should use persistence for its position, but let the size be forced to whatever I want.

**Comment by emilk** [comment]
ok, that makes sense... so even more fine control over persistence. feel free to open an feature request issue on that
