### ISSUE TITLE
Generating random `Id`s

### ISSUE THREAD

**Issue by mankinskin** [emilk/egui#661]
It would be useful to have some integrated facility to generate a random `Id` for new elements.
Sometimes we need an `Id` before rendering an element, so we explicitly generate one. Currently we do this by using some inherent state of the element we want to render as a hashing seed. This is problematic when there is either no hashable inherent state we can use or when we want to render two instances of the exact same element. We need to manage some global state that changes for each element we want to create, for example a counter or system time.

I think in addition to a deterministic way to generate id's, like we have now, using `Id::new(impl Hash)`, we could use something like `Context::new_random_id()` and `Context::set_id_generation_seed(impl Hash)`. Maybe even something like an `IdGenerator` makes sense.

**Comment by TimonPost** [comment]
It seems that this could be implemented on the user side rather than the core engine. It needs to be decided whether it falls under the core vision of egui to support additional features that are "nice to have". I would be of the opinion that the less global state the better. 

There are some potential implementation concerns:
- Very small capability: Repeatedly generated ID. 
- Needs an extra thread to generate random numbers (depending on the random gen approach).
- Needs a feature flag, I assume this random feature will not be used universally.

**Comment by emilk** [comment]
> It seems that this could be implemented on the user side

I agree – this is pretty simple to add in your own code:

``` rust
pub fn random_id() -> egui::Id {
   egui::Id::from_u64(rand::thread_rng().gen())
}
```

(there is no `Id::from_u64` right now, but we could add it).
