### ISSUE TITLE
New window

### ISSUE THREAD

**Issue by LoggedHeader** [emilk/egui#751]
I would like to use egui to render an overlay that displays the players stats in my game.

For context, I would like to keep the overlay internal.
I would do this by injecting my dll into the game and hooking wglSwapBuffers where I would then render my overlay.

But it seems like this isn't possible with the current OpenGL implementations because they force you to create a new window.

Am I missing something in these implementations that will allow me to render my overlay without creating a new window
or do I have to implement this myself?

**Comment by emilk** [comment]
Perhaps you can reuse https://docs.rs/egui_glium/0.14.0/egui_glium/struct.Painter.html for this, but I don't know.

**Comment by coderedart** [comment]
This confusion comes up because egui is often confused and mixed up with its fellow brothers like egui_glium or epi/eframe. 
egui itself doesn't have a concept of the window or anything. you can just create a new CtxRef, add all stuff it needs to RawInput like screen size, position etc.. and finally just get the output to draw however you want. 

You will need to take care of the drawing yourself manually with opengl or whatever api you are hooking into. if its just opengl, you can copy the egui render code from the other popular crates easily. but the events though, I have no idea how the hooking deals with that.
