### ISSUE TITLE
Expose `layout_in_ui` or `paint_galley` method on `egui::widgets::Label` for custom Hyperlink widgets

### ISSUE THREAD

**Issue by mushogenshin** [emilk/egui#767]
I'd like to implement custom **Hyperlink** widget that instead of opening a URL it reveals the **Finder** (on MacOS) -- or shows the **File Explorer** (on Windows) --, but both method `layout_in_ui` and `paint_galley` are private.

Please consider exposing the method(s) for public use.

Without it I think I can only resort to using regular buttons.

I received the warnings at:
`label.paint_galley(ui, rect.min, galley);` (if mimicking latest crates.io source) 
and
`let (pos, galley, response) =   label.layout_in_ui(ui);` (if mimicking latest GitHub source)

Thanks so much!

**Comment by emilk** [comment]
I think all methods that `Hyperlink` use are now `pub`.

…but to change what happens when clicking a `Hyperlink`, I think it would make more sense to have that as a built-in widget.

e.g. a `Link` widget which doesn't do anything, and it is up to the user to handle `.clicked()` on the response (just like `Button`). Then `Hyperlink` can just be a very simple widget wrapping `Link`.

**Comment by emilk** [comment]
Actually, the above suggestion was already discussed in https://github.com/emilk/egui/issues/1152
