### ISSUE TITLE
Widget Gallery

### ISSUE THREAD

**Issue by Lowentwickler** [emilk/egui#88]
Hello and Happy upcoming New Year!

I am doing integration between EGUI and our game engine [Dotrix](https://github.com/lowenware/dotrix). We don't have our UI crate yet and I am about to use EGUI for an editor for now. Results looks like this so far
<img width="912" alt="Snímek obrazovky 2020-12-30 v 23 31 59" src="https://user-images.githubusercontent.com/5078803/103417076-8cd05b80-4b89-11eb-9f51-724139bf322d.png">

My question if there is already some widget gallery maybe as an image with widgets and their names? Or should I just refer this list https://docs.rs/egui/0.6.0/egui/widgets/index.html ?

**Comment by emilk** [comment]
Hello, and happy 2021!

At the moment the only widget gallery is the one at <https://emilk.github.io/egui/index.html#demo>. It is not extremely well structured, but it covers most of the widgets.

**Comment by Lowentwickler** [comment]
Thank you! And is there a way to catch  "changed" event for lets say Slider wigdet?

**Comment by emilk** [comment]
There is `response.active` which is `true` whilst a slider is being dragged: https://docs.rs/egui/0.7.0/egui/struct.Response.html#structfield.active

**Comment by emilk** [comment]
<img width="352" alt="widget_gallery" src="https://user-images.githubusercontent.com/1148717/104232710-05200200-5451-11eb-84f3-ca08062a544d.png">

**Comment by virtualritz** [comment]
So to follow up from twitter. The above looks great. As a professional pixelfucker™ I have some suggestions. 😉

I will refer to the text in the left column as `labels` and the text in the right column as `widget text`.
1. Match labels and widget text font sizes. At least make sure widget text font size is never larger than label font size.
2. Align baselines of label and widget text (shown blue line in image below) – this is already good in many places but could be improved in some.
3. Give labels and widget text room to 'breathe' on the left and right. Examples are all labels (left side), `SelectableLabel:` (roght side) and text entry, menu button/combobox and boolean toggle button texts. They feel 'squeezed' in their widgets.
4. Widget text coloring seems inconsistent. What does bright mean/what does dull mean?
5. Probably on your radar anyway: antialiasing on `Slider:`/`DragValue:` text.

In general I think vertical spacing can have some breathing room. Hopefully this will simply be a parameter.

<img width="322" alt="Screen Shot 2021-01-09 at 17 44 23_fixed_lines" src="https://user-images.githubusercontent.com/387036/104336071-4ae1d680-54f4-11eb-85f2-17cf80f34b8e.png">

In the image above there is another subtle detail. Within the first row, the input text box is *mathematically* centered. 2px top and bottom.
However, the slider and the checkbox on rows two and three are *optically* centered. 3px top and 5px bottom. 
This looks better than having them 4px at top and bottom. Probably 3px and 4px would work even better but I used an even row height and was too lazy to change my mockup later. 😜
_Optical_ centering with 1px and 3px does _not_ work for the text input in row one because you barely can see the a 1px spacing.

This is very subtle but imho these things make the difference why some UIs look good why others not only look good but also polished.

P.S.: I love that you did the alternating background color!

**Comment by emilk** [comment]
@virtualritz a lot of good suggestions, and the good news is that most are already in the works :) directly after posting the screenshot I also became annoyed with basically the same things you mentioned, and started tweaking. Expect an update later this week.

About the colors and sizes: clickable things use a larger font and brighter colors (with some exceptions, which will be fixed). Not saying that's a good thing, but there is a logic.

About the monospace font: feel free to find and suggest an alternative. The current one (ProggyClean) has the benefit of being very readable on low-dpi screens, but yeah, it is pixly.

**Comment by virtualritz** [comment]
For the monospaced font: I would use a proportional font (same as the rest) for those drag value boxes and always center the text inside the box. That is easy to implement and will look reasonable. A better solution is to use the widest number character in the font as the width and typeset the font monospaced, even if it is poroportional.

**Comment by virtualritz** [comment]
> @virtualritz a lot of good suggestions, and the good news is that most are already in the works :) directly after posting the screenshot I also became annoyed with basically the same things you mentioned, and started tweaking. Expect an update later this week. Polish and beauty matters!

That is awesome!!!

**Comment by virtualritz** [comment]
On that note: this kind of grid-based UI with a fixed size label are on the left is what people writing desktop app need for adding interfaces to editors, creative coding apps, viewers, preference dialogs etc. 90% of the time from my experience.

I.e. if a GUI toolkit for desktop apps has good out-of-the-box support for this it makes it the strongest reason for peeps like me to use that toolkit over others.

Aka: when this is part of `Egui` someone should write a blog post just about *this* feature.
Not least to inspire others (`iced` etc) to offer something similar.

**Comment by virtualritz** [comment]
Below screenshot is from AfterEffects which has one of the cleanest layouts of this kind (imho). I checked and what they do is for the collapsed sliders (that turn into drag values, when collapsed) to use monospaced numbers.
But within the same font (so they probably typeset them monospaced). Below, at the bottom, `Iterations` is an example of a collapsed slider with integer value. For float values they just left-align the text. I.e. numbers are monospaced but the decimal dot is proportional (see `Feather` in the screenshot).

Another interesting thing is the circle in front of each many labels, on the left. This is to set a keyframe. Not the nice indentation too.

<img width="361" alt="Screen Shot 2021-01-12 at 20 00 08" src="https://user-images.githubusercontent.com/387036/104360114-da957e00-5510-11eb-8904-bdd96cfa18da.png">

**Comment by virtualritz** [comment]
So I checked, a good font will have the unicode characters for monospaced numbers 0..9.
Here they are as UTF8 (mathematical monospaced digit 0..9): 𝟶𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿

[This article](https://viljamis.com/2016/typography-for-user-interfaces/) mentions [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro) as a font for UIs. I like that it is a bit condensed.

**Comment by emilk** [comment]
Egui 0.8.0 has been released with the grid layout, and the widget gallery can be tested at https://emilk.github.io/egui/#demo

I spend a lot of time on the new style, and getting all the text to align correctly (fixing quite a few bugs in the process). I am happy with how it ended up, and I'll leave it like this for now.

Here is the final version:

![widget_gallery_0 8 0](https://user-images.githubusercontent.com/1148717/104846615-b7394d00-58db-11eb-9b29-f72e1240555a.gif)

**Comment by virtualritz** [comment]
This looks super nice!!!

Is there a way to make a group of widgets in such a grid that can be collapsed w/o the full label area width indentation in `Collapsing Header`? I.e. I tried adding another grid under `Collapsing Header` and it works but it is indented too much.
More like in the screenshot from AfterEffects, e.g. the `Matte` & `Tracking Data` widget groups?

**Comment by emilk** [comment]
No, that is not currently possible. `egui::Grid` is currently a strict grid, where nothing can cover multiple cells (like e.g. the Feather slider does). It is not obvious to me how one would align children of two different collapsing headers. What is needed it some sort of "tab stops" (like those in a word processor) that live in some parent Ui, and some way to reference them?
