### ISSUE TITLE
Window is not resized because of limit, but window content do

### ISSUE THREAD

**Issue by optozorax** [emilk/egui#94]
I think this is a bug.

https://user-images.githubusercontent.com/18114381/103560352-38f7a680-4eea-11eb-98f8-6328c1d95a03.mp4

**Comment by emilk** [comment]
This is actually intended (if admittedly confusing) behavior! 

You are attempting to make the window thinner than the widest widget, and that's not possible (because there is no horizontal scrolling which could allow that). So why is Egui so early wrapping the text only to then not make the window thin?

It turns out that because Egui is an immediate mode GUI, Egui can't know whether or not there will be a wide widget in the window until that widget is added (which is outside the frame of this video). So Egui will optimistically make all widgets fit in to the thin window (which is why you see the text wrap etc) but will then "abort" the shrinking when the widget widget is added. But then it is too late to go back!

There is, as far as I can tell, only one way to solve this (in an immediate mode GUI), which is to add horizontal scroll bars to windows (and thereby forcing you to scroll sideways when you shrink a window by a lot). I haven't gotten around to implementing that yet, but even if I had I think I would disable it by default for most windows (because I'd prefer not to be able to shrink windows beyond the widest widgets).

I do agree that it looks quite glitchy, and I'm open to suggestions on how to improve that. Maybe there could be some helpful visual feedback to show that the window couldn't become as thin as requested.
