### ISSUE TITLE
Unexpected behaviour of `drag_window`

### ISSUE THREAD

**Issue by feelingnothing** [emilk/egui#943]
![result](https://user-images.githubusercontent.com/47575622/145481036-e49d40a3-f52b-4bf5-a638-01a0d65d693e.gif)

**Comment by feelingnothing** [comment]
![result](https://user-images.githubusercontent.com/47575622/145485061-e3b75eb7-4aea-4a53-a5d2-868d82b4eb4d.gif)
After some test i figured that on windows it requires being called only on start, but losing focus after possible only with cursor going out of application

**Comment by emilk** [comment]
Perhaps `winit::Window::drag_window` should only be called once (even if an egui app sets the `drag_window` flag many frames). Since everything works well on my mac it is hard for me to figure out. Perhaps you can take a look at `egui-winit/src/epi.rs` and see if you can fix it? `egui-winit` would need to save some state (`is_dragging_window`) and then only call `drag_window` if `drag_window && !is_dragging_window`.

**Comment by AlexxxRu** [comment]
I've checked this bug and looks like we should call `drag_window()` only after the mouse left click.
It works fine, but I'm not sure how it can work with touch screens. Do we have the same event from winit?

@emik what do you think about it? 
https://github.com/emilk/egui/pull/1108

**Comment by AlexxxRu** [comment]
But this solution is still far from the best. The application should call `drag_window` just after LMB [drag_window](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.drag_window).
For now, `drag_window` is called only during the redraw event. And I'm not sure how we can get frame output just after LMB.
